//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//! upnp_validate_3+2d+k_advertisements_0051.script
//! @SYMTestSuiteName	multiple_machines_server 
//! @SYMScriptTestEnvironment

PRINT Run all multiple_machines_server 

LOAD_SUITE multiple_machines_server

START_TESTCASE	upnp_validate_3+2d+k_advertisements_0051
//! @file					
//! @SYMTestCaseID			UPNP - POS - 0051
//! @SYMTestCaseDesc 		Service point should be able to advertise itself as soon as it joins the UPnP LAN (Notify with NTS:ssdp:alive)
//! @SYMREQ					REQ8617 REQ8618 REQ8619
//! @SYMTestStatus 			Implemented
//! @SYMTestPriority 		1
//! @SYMTestActions 		1.	Join a Service point to UPnP enabled network.
//! 						2.	Service point multicasts advertisements with NOTIFY method and sddp:alive in the NTS header for all its service types and devices.
//! @SYMTestExpectedResults	Validate 3+2d+k Discovery advertisements are advertised. i.e.,
//!								If there is an UPnP enabled root device then it is expected to send 3+2d+k advertisements per root device.
//!								If there are only non-root devices then each of them are expected to send only 2d+k advertisements.
//! @SYMTestType 			CIT
RUN_TEST_STEP 500  multiple_machines_server TestUPnPManager z:\upnp\testupnp\client\testdata\ini_files\register_0036.ini upnp_validate_3+2d+k_server
END_TESTCASE	upnp_validate_3+2d+k_advertisements_0051