//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//! @file
//! @SYMTestSuiteName	multiple_machines_client 
//! @SYMScriptTestEnvironment

PRINT Run all multiple_machines_client 

LOAD_SUITE multiple_machines_client
LOAD_SUITE test_synchronize_client
LOAD_SUITE testdelay

START_TESTCASE	UPnP_Discovery_0013
//! @file		
//! @SYMTestCaseID	upnp-pos-0009
//! @SYMTestCaseDesc 	Search for UPnP Device based on its UUID second version
//! @SYMREQ		REQ8605,REQ8606,REQ8607
//! @SYMTestStatus 	Implemented
//! @SYMTestPriority 	High
//! @SYMTestActions 	Search for UPnP Device based on its UUID second version
//! @SYMTestExpectedResults Should get response from the desired UUID only	
//! @SYMTestType 		CIT

RUN_TEST_STEP 1000 testdelay TestUPnPManager  
RUN_TEST_STEP 1000 testdelay TestUPnPManager
RUN_TEST_STEP 1000 test_synchronize_client TestUPnPManager  z:\upnp\testupnp\client\testdata\ini_files\test_synchronize_client.ini clientdata
RUN_TEST_STEP 500 multiple_machines_client TestUPnPManager z:\upnp\testupnp\client\testdata\ini_files\discovery0013.ini discovery_0013
END_TESTCASE	UPnP_Discovery_0013


PRINT Completed multiple_machines_client
