//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//upnp_register_state_change_services_0038.script
//! @SYMTestSuiteName	testupnp 
//! @SYMScriptTestEnvironment

PRINT Run all multiple_machines_client 

LOAD_SUITE multiple_machines_client
LOAD_SUITE testdelay

START_TESTCASE	upnp_register_state_change_services_0038
//! @file					
//! @SYMTestCaseID			UPNP - POS - 0038
//! @SYMTestCaseDesc 		Control point registers for state changes in services.
//! @SYMREQ 				REQ8634
//! @SYMTestStatus 			Implemented
//! @SYMTestPriority 		1
//! @SYMTestActions 		1.	Control point issues GENA’s SUBSCRIBE request to an event with NT and CALLBACK headers 
//! 						2.	If requested subscription is approved then Service point must acknowledge with SID and TIMEOUT, else with appropriate error message. 
//! @SYMTestExpectedResults	If subscription is approved then control point gets an SID else an appropriate error message.
//! @SYMTestType 			CIT

RUN_TEST_STEP 1000 testdelay TestUPnPManager  
RUN_TEST_STEP 1000 testdelay TestUPnPManager
RUN_TEST_STEP 300 multiple_machines_client TestUPnPManager z:\upnp\testupnp\client\testdata\ini_files\subscribe_0038.ini  UPnP_Subscribe_0001
RUN_TEST_STEP 300 multiple_machines_client TestUPnPManager z:\upnp\testupnp\client\testdata\ini_files\subscribe_0038.ini  UPnP_Subscribe_0002

END_TESTCASE	upnp_register_state_change_services_0038
