//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//! discover_low_ver.script
//! @SYMTestSuiteName	multiple_machines_server 
//! @SYMScriptTestEnvironment

PRINT Run all multiple_machines_server 

LOAD_SUITE multiple_machines_server
LOAD_SUITE test_synchronize_server

START_TESTCASE	UPNP_DISCOVER_LOW_VER
//! @file		
//! @SYMTestCaseID	
//! @SYMTestCaseDesc 	
//! @SYMREQ				REQ8608, REQ8605,REQ8606,REQ8607, REQ8617,REQ8618	
//! @SYMTestStatus 	Implemented
//! @SYMTestPriority 	High	
//! @SYMTestActions 	
//! @SYMTestExpectedResults 
//! @SYMTestType 		CIT


RUN_TEST_STEP 1000 test_synchronize_server TestUPnPManager  z:\upnp\testupnp\client\testdata\ini_files\test_synchronize_client.ini serverdata
RUN_TEST_STEP 500 multiple_machines_server TestUPnPManager z:\upnp\testupnp\client\testdata\ini_files\discover_low_ver.ini UPnP_discover_low_ver_0021_server
END_TESTCASE	UPNP_DISCOVER_LOW_VER


PRINT Completed multiple_machines_server
