/*
 * THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT.
 *
 *
 * Copyright (C) 2005 Apple Computer, Inc.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE COMPUTER, INC. ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE COMPUTER, INC. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. 
 */


#include "config.h"
#ifdef AVOID_STATIC_CONSTRUCTORS
#define DOM_HTMLNAMES_HIDE_GLOBALS 1
#else
#define QNAME_DEFAULT_CONSTRUCTOR 1
#endif

#include "HTMLNames.h"
#include "StaticConstructors.h"
namespace WebCore { namespace HTMLNames {

using namespace WebCore;

static bool initialized = false;

static const char *xhtmlNSString = "http://www.w3.org/1999/xhtml";
// Tags
static const char *aTagString = "a";
static const char *abbrTagString = "abbr";
static const char *acronymTagString = "acronym";
static const char *addressTagString = "address";
static const char *appletTagString = "applet";
static const char *areaTagString = "area";
static const char *bTagString = "b";
static const char *baseTagString = "base";
static const char *basefontTagString = "basefont";
static const char *bdoTagString = "bdo";
static const char *bgsoundTagString = "bgsound";
static const char *bigTagString = "big";
static const char *blockquoteTagString = "blockquote";
static const char *bodyTagString = "body";
static const char *brTagString = "br";
static const char *buttonTagString = "button";
static const char *canvasTagString = "canvas";
static const char *captionTagString = "caption";
static const char *centerTagString = "center";
static const char *citeTagString = "cite";
static const char *codeTagString = "code";
static const char *colTagString = "col";
static const char *colgroupTagString = "colgroup";
static const char *ddTagString = "dd";
static const char *delTagString = "del";
static const char *dfnTagString = "dfn";
static const char *dirTagString = "dir";
static const char *divTagString = "div";
static const char *dlTagString = "dl";
static const char *dtTagString = "dt";
static const char *emTagString = "em";
static const char *embedTagString = "embed";
static const char *fieldsetTagString = "fieldset";
static const char *fontTagString = "font";
static const char *formTagString = "form";
static const char *frameTagString = "frame";
static const char *framesetTagString = "frameset";
static const char *headTagString = "head";
static const char *h1TagString = "h1";
static const char *h2TagString = "h2";
static const char *h3TagString = "h3";
static const char *h4TagString = "h4";
static const char *h5TagString = "h5";
static const char *h6TagString = "h6";
static const char *hrTagString = "hr";
static const char *htmlTagString = "html";
static const char *iTagString = "i";
static const char *iframeTagString = "iframe";
static const char *imageTagString = "image";
static const char *imgTagString = "img";
static const char *inputTagString = "input";
static const char *insTagString = "ins";
static const char *isindexTagString = "isindex";
static const char *kbdTagString = "kbd";
static const char *keygenTagString = "keygen";
static const char *labelTagString = "label";
static const char *layerTagString = "layer";
static const char *legendTagString = "legend";
static const char *liTagString = "li";
static const char *linkTagString = "link";
static const char *listingTagString = "listing";
static const char *mapTagString = "map";
static const char *marqueeTagString = "marquee";
static const char *menuTagString = "menu";
static const char *metaTagString = "meta";
static const char *nobrTagString = "nobr";
static const char *noembedTagString = "noembed";
static const char *noframesTagString = "noframes";
static const char *nolayerTagString = "nolayer";
static const char *noscriptTagString = "noscript";
static const char *objectTagString = "object";
static const char *olTagString = "ol";
static const char *optgroupTagString = "optgroup";
static const char *optionTagString = "option";
static const char *pTagString = "p";
static const char *paramTagString = "param";
static const char *plaintextTagString = "plaintext";
static const char *preTagString = "pre";
static const char *qTagString = "q";
static const char *sTagString = "s";
static const char *sampTagString = "samp";
static const char *scriptTagString = "script";
static const char *selectTagString = "select";
static const char *smallTagString = "small";
static const char *spanTagString = "span";
static const char *strikeTagString = "strike";
static const char *strongTagString = "strong";
static const char *styleTagString = "style";
static const char *subTagString = "sub";
static const char *supTagString = "sup";
static const char *tableTagString = "table";
static const char *tbodyTagString = "tbody";
static const char *tdTagString = "td";
static const char *textareaTagString = "textarea";
static const char *tfootTagString = "tfoot";
static const char *thTagString = "th";
static const char *theadTagString = "thead";
static const char *titleTagString = "title";
static const char *trTagString = "tr";
static const char *ttTagString = "tt";
static const char *uTagString = "u";
static const char *ulTagString = "ul";
static const char *varTagString = "var";
static const char *wbrTagString = "wbr";
static const char *xmpTagString = "xmp";
// Attributes
static const char *abbrAttrString = "abbr";
static const char *accept_charsetAttrString = "accept_charset";
static const char *acceptAttrString = "accept";
static const char *accesskeyAttrString = "accesskey";
static const char *actionAttrString = "action";
static const char *alignAttrString = "align";
static const char *alinkAttrString = "alink";
static const char *altAttrString = "alt";
static const char *archiveAttrString = "archive";
static const char *autocompleteAttrString = "autocomplete";
static const char *autosaveAttrString = "autosave";
static const char *axisAttrString = "axis";
static const char *backgroundAttrString = "background";
static const char *behaviorAttrString = "behavior";
static const char *bgcolorAttrString = "bgcolor";
static const char *bgpropertiesAttrString = "bgproperties";
static const char *borderAttrString = "border";
static const char *bordercolorAttrString = "bordercolor";
static const char *cellpaddingAttrString = "cellpadding";
static const char *cellspacingAttrString = "cellspacing";
static const char *charAttrString = "char";
static const char *challengeAttrString = "challenge";
static const char *charoffAttrString = "charoff";
static const char *charsetAttrString = "charset";
static const char *checkedAttrString = "checked";
static const char *cellborderAttrString = "cellborder";
static const char *citeAttrString = "cite";
static const char *classAttrString = "class";
static const char *classidAttrString = "classid";
static const char *clearAttrString = "clear";
static const char *codeAttrString = "code";
static const char *codebaseAttrString = "codebase";
static const char *codetypeAttrString = "codetype";
static const char *colorAttrString = "color";
static const char *colsAttrString = "cols";
static const char *colspanAttrString = "colspan";
static const char *compactAttrString = "compact";
static const char *compositeAttrString = "composite";
static const char *contentAttrString = "content";
static const char *contenteditableAttrString = "contenteditable";
static const char *coordsAttrString = "coords";
static const char *ctiAttrString = "cti";
static const char *dataAttrString = "data";
static const char *datetimeAttrString = "datetime";
static const char *declareAttrString = "declare";
static const char *deferAttrString = "defer";
static const char *dirAttrString = "dir";
static const char *directionAttrString = "direction";
static const char *directkeyAttrString = "directkey";
static const char *disabledAttrString = "disabled";
static const char *emailAttrString = "email";
static const char *enctypeAttrString = "enctype";
static const char *faceAttrString = "face";
static const char *forAttrString = "for";
static const char *frameAttrString = "frame";
static const char *frameborderAttrString = "frameborder";
static const char *headersAttrString = "headers";
static const char *heightAttrString = "height";
static const char *hiddenAttrString = "hidden";
static const char *hrefAttrString = "href";
static const char *hreflangAttrString = "hreflang";
static const char *hspaceAttrString = "hspace";
static const char *http_equivAttrString = "http_equiv";
static const char *idAttrString = "id";
static const char *incrementalAttrString = "incremental";
static const char *ismapAttrString = "ismap";
static const char *keytypeAttrString = "keytype";
static const char *labelAttrString = "label";
static const char *langAttrString = "lang";
static const char *languageAttrString = "language";
static const char *leftAttrString = "left";
static const char *leftmarginAttrString = "leftmargin";
static const char *linkAttrString = "link";
static const char *longdescAttrString = "longdesc";
static const char *loopAttrString = "loop";
static const char *lowsrcAttrString = "lowsrc";
static const char *marginheightAttrString = "marginheight";
static const char *marginwidthAttrString = "marginwidth";
static const char *maxAttrString = "max";
static const char *maxlengthAttrString = "maxlength";
static const char *mayscriptAttrString = "mayscript";
static const char *mediaAttrString = "media";
static const char *methodAttrString = "method";
static const char *minAttrString = "min";
static const char *multipleAttrString = "multiple";
static const char *nameAttrString = "name";
static const char *nohrefAttrString = "nohref";
static const char *noresizeAttrString = "noresize";
static const char *noshadeAttrString = "noshade";
static const char *nowrapAttrString = "nowrap";
static const char *objectAttrString = "object";
static const char *onabortAttrString = "onabort";
static const char *onbeforecopyAttrString = "onbeforecopy";
static const char *onbeforecutAttrString = "onbeforecut";
static const char *onbeforepasteAttrString = "onbeforepaste";
static const char *onbeforeunloadAttrString = "onbeforeunload";
static const char *onblurAttrString = "onblur";
static const char *onchangeAttrString = "onchange";
static const char *onclickAttrString = "onclick";
static const char *oncontextmenuAttrString = "oncontextmenu";
static const char *oncopyAttrString = "oncopy";
static const char *oncutAttrString = "oncut";
static const char *ondblclickAttrString = "ondblclick";
static const char *ondragAttrString = "ondrag";
static const char *ondragendAttrString = "ondragend";
static const char *ondragenterAttrString = "ondragenter";
static const char *ondragleaveAttrString = "ondragleave";
static const char *ondragoverAttrString = "ondragover";
static const char *ondragstartAttrString = "ondragstart";
static const char *ondropAttrString = "ondrop";
static const char *onerrorAttrString = "onerror";
static const char *onfocusAttrString = "onfocus";
static const char *oninputAttrString = "oninput";
static const char *onkeydownAttrString = "onkeydown";
static const char *onkeypressAttrString = "onkeypress";
static const char *onkeyupAttrString = "onkeyup";
static const char *onloadAttrString = "onload";
static const char *onmousedownAttrString = "onmousedown";
static const char *onmousemoveAttrString = "onmousemove";
static const char *onmouseoutAttrString = "onmouseout";
static const char *onmouseoverAttrString = "onmouseover";
static const char *onmouseupAttrString = "onmouseup";
static const char *onmousewheelAttrString = "onmousewheel";
static const char *onpasteAttrString = "onpaste";
static const char *onresetAttrString = "onreset";
static const char *onresizeAttrString = "onresize";
static const char *onscrollAttrString = "onscroll";
static const char *onsearchAttrString = "onsearch";
static const char *onselectAttrString = "onselect";
static const char *onselectstartAttrString = "onselectstart";
static const char *onsubmitAttrString = "onsubmit";
static const char *onunloadAttrString = "onunload";
static const char *pagexAttrString = "pagex";
static const char *pageyAttrString = "pagey";
static const char *placeholderAttrString = "placeholder";
static const char *plainAttrString = "plain";
static const char *pluginpageAttrString = "pluginpage";
static const char *pluginspageAttrString = "pluginspage";
static const char *pluginurlAttrString = "pluginurl";
static const char *precisionAttrString = "precision";
static const char *profileAttrString = "profile";
static const char *promptAttrString = "prompt";
static const char *readonlyAttrString = "readonly";
static const char *relAttrString = "rel";
static const char *resultsAttrString = "results";
static const char *revAttrString = "rev";
static const char *rowsAttrString = "rows";
static const char *rowspanAttrString = "rowspan";
static const char *rulesAttrString = "rules";
static const char *schemeAttrString = "scheme";
static const char *scopeAttrString = "scope";
static const char *scrollamountAttrString = "scrollamount";
static const char *scrolldelayAttrString = "scrolldelay";
static const char *scrollingAttrString = "scrolling";
static const char *selectedAttrString = "selected";
static const char *shapeAttrString = "shape";
static const char *sizeAttrString = "size";
static const char *soundstartAttrString = "soundstart";
static const char *spanAttrString = "span";
static const char *srcAttrString = "src";
static const char *standbyAttrString = "standby";
static const char *startAttrString = "start";
static const char *styleAttrString = "style";
static const char *summaryAttrString = "summary";
static const char *tabindexAttrString = "tabindex";
static const char *tableborderAttrString = "tableborder";
static const char *targetAttrString = "target";
static const char *telbookAttrString = "telbook";
static const char *textAttrString = "text";
static const char *titleAttrString = "title";
static const char *topAttrString = "top";
static const char *topmarginAttrString = "topmargin";
static const char *truespeedAttrString = "truespeed";
static const char *typeAttrString = "type";
static const char *usemapAttrString = "usemap";
static const char *valignAttrString = "valign";
static const char *valueAttrString = "value";
static const char *valuetypeAttrString = "valuetype";
static const char *versionAttrString = "version";
static const char *viewsourceAttrString = "viewsource";
static const char *vlinkAttrString = "vlink";
static const char *volumeAttrString = "volume";
static const char *vspaceAttrString = "vspace";
static const char *widthAttrString = "width";
static const char *wrapAttrString = "wrap";

DEFINE_GLOBAL(AtomicString, xhtmlNamespaceURI, "http://www.w3.org/1999/xhtml")
// Tags
DEFINE_GLOBAL(QualifiedName, aTag, nullAtom, "a", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, abbrTag, nullAtom, "abbr", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, acronymTag, nullAtom, "acronym", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, addressTag, nullAtom, "address", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, appletTag, nullAtom, "applet", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, areaTag, nullAtom, "area", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, bTag, nullAtom, "b", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, baseTag, nullAtom, "base", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, basefontTag, nullAtom, "basefont", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, bdoTag, nullAtom, "bdo", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, bgsoundTag, nullAtom, "bgsound", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, bigTag, nullAtom, "big", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, blockquoteTag, nullAtom, "blockquote", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, bodyTag, nullAtom, "body", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, brTag, nullAtom, "br", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, buttonTag, nullAtom, "button", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, canvasTag, nullAtom, "canvas", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, captionTag, nullAtom, "caption", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, centerTag, nullAtom, "center", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, citeTag, nullAtom, "cite", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, codeTag, nullAtom, "code", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, colTag, nullAtom, "col", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, colgroupTag, nullAtom, "colgroup", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, ddTag, nullAtom, "dd", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, delTag, nullAtom, "del", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, dfnTag, nullAtom, "dfn", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, dirTag, nullAtom, "dir", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, divTag, nullAtom, "div", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, dlTag, nullAtom, "dl", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, dtTag, nullAtom, "dt", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, emTag, nullAtom, "em", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, embedTag, nullAtom, "embed", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, fieldsetTag, nullAtom, "fieldset", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, fontTag, nullAtom, "font", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, formTag, nullAtom, "form", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, frameTag, nullAtom, "frame", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, framesetTag, nullAtom, "frameset", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, headTag, nullAtom, "head", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, h1Tag, nullAtom, "h1", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, h2Tag, nullAtom, "h2", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, h3Tag, nullAtom, "h3", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, h4Tag, nullAtom, "h4", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, h5Tag, nullAtom, "h5", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, h6Tag, nullAtom, "h6", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, hrTag, nullAtom, "hr", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, htmlTag, nullAtom, "html", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, iTag, nullAtom, "i", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, iframeTag, nullAtom, "iframe", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, imageTag, nullAtom, "image", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, imgTag, nullAtom, "img", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, inputTag, nullAtom, "input", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, insTag, nullAtom, "ins", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, isindexTag, nullAtom, "isindex", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, kbdTag, nullAtom, "kbd", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, keygenTag, nullAtom, "keygen", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, labelTag, nullAtom, "label", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, layerTag, nullAtom, "layer", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, legendTag, nullAtom, "legend", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, liTag, nullAtom, "li", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, linkTag, nullAtom, "link", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, listingTag, nullAtom, "listing", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, mapTag, nullAtom, "map", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, marqueeTag, nullAtom, "marquee", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, menuTag, nullAtom, "menu", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, metaTag, nullAtom, "meta", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, nobrTag, nullAtom, "nobr", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, noembedTag, nullAtom, "noembed", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, noframesTag, nullAtom, "noframes", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, nolayerTag, nullAtom, "nolayer", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, noscriptTag, nullAtom, "noscript", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, objectTag, nullAtom, "object", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, olTag, nullAtom, "ol", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, optgroupTag, nullAtom, "optgroup", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, optionTag, nullAtom, "option", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, pTag, nullAtom, "p", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, paramTag, nullAtom, "param", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, plaintextTag, nullAtom, "plaintext", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, preTag, nullAtom, "pre", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, qTag, nullAtom, "q", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, sTag, nullAtom, "s", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, sampTag, nullAtom, "samp", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, scriptTag, nullAtom, "script", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, selectTag, nullAtom, "select", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, smallTag, nullAtom, "small", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, spanTag, nullAtom, "span", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, strikeTag, nullAtom, "strike", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, strongTag, nullAtom, "strong", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, styleTag, nullAtom, "style", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, subTag, nullAtom, "sub", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, supTag, nullAtom, "sup", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, tableTag, nullAtom, "table", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, tbodyTag, nullAtom, "tbody", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, tdTag, nullAtom, "td", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, textareaTag, nullAtom, "textarea", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, tfootTag, nullAtom, "tfoot", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, thTag, nullAtom, "th", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, theadTag, nullAtom, "thead", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, titleTag, nullAtom, "title", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, trTag, nullAtom, "tr", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, ttTag, nullAtom, "tt", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, uTag, nullAtom, "u", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, ulTag, nullAtom, "ul", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, varTag, nullAtom, "var", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, wbrTag, nullAtom, "wbr", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, xmpTag, nullAtom, "xmp", xhtmlNamespaceURI);


WebCore::QualifiedName** getHTMLTags(size_t* size)
{
    static WebCore::QualifiedName* HTMLTags[] = {
        (WebCore::QualifiedName*)&aTag,
        (WebCore::QualifiedName*)&abbrTag,
        (WebCore::QualifiedName*)&acronymTag,
        (WebCore::QualifiedName*)&addressTag,
        (WebCore::QualifiedName*)&appletTag,
        (WebCore::QualifiedName*)&areaTag,
        (WebCore::QualifiedName*)&bTag,
        (WebCore::QualifiedName*)&baseTag,
        (WebCore::QualifiedName*)&basefontTag,
        (WebCore::QualifiedName*)&bdoTag,
        (WebCore::QualifiedName*)&bgsoundTag,
        (WebCore::QualifiedName*)&bigTag,
        (WebCore::QualifiedName*)&blockquoteTag,
        (WebCore::QualifiedName*)&bodyTag,
        (WebCore::QualifiedName*)&brTag,
        (WebCore::QualifiedName*)&buttonTag,
        (WebCore::QualifiedName*)&canvasTag,
        (WebCore::QualifiedName*)&captionTag,
        (WebCore::QualifiedName*)&centerTag,
        (WebCore::QualifiedName*)&citeTag,
        (WebCore::QualifiedName*)&codeTag,
        (WebCore::QualifiedName*)&colTag,
        (WebCore::QualifiedName*)&colgroupTag,
        (WebCore::QualifiedName*)&ddTag,
        (WebCore::QualifiedName*)&delTag,
        (WebCore::QualifiedName*)&dfnTag,
        (WebCore::QualifiedName*)&dirTag,
        (WebCore::QualifiedName*)&divTag,
        (WebCore::QualifiedName*)&dlTag,
        (WebCore::QualifiedName*)&dtTag,
        (WebCore::QualifiedName*)&emTag,
        (WebCore::QualifiedName*)&embedTag,
        (WebCore::QualifiedName*)&fieldsetTag,
        (WebCore::QualifiedName*)&fontTag,
        (WebCore::QualifiedName*)&formTag,
        (WebCore::QualifiedName*)&frameTag,
        (WebCore::QualifiedName*)&framesetTag,
        (WebCore::QualifiedName*)&headTag,
        (WebCore::QualifiedName*)&h1Tag,
        (WebCore::QualifiedName*)&h2Tag,
        (WebCore::QualifiedName*)&h3Tag,
        (WebCore::QualifiedName*)&h4Tag,
        (WebCore::QualifiedName*)&h5Tag,
        (WebCore::QualifiedName*)&h6Tag,
        (WebCore::QualifiedName*)&hrTag,
        (WebCore::QualifiedName*)&htmlTag,
        (WebCore::QualifiedName*)&iTag,
        (WebCore::QualifiedName*)&iframeTag,
        (WebCore::QualifiedName*)&imageTag,
        (WebCore::QualifiedName*)&imgTag,
        (WebCore::QualifiedName*)&inputTag,
        (WebCore::QualifiedName*)&insTag,
        (WebCore::QualifiedName*)&isindexTag,
        (WebCore::QualifiedName*)&kbdTag,
        (WebCore::QualifiedName*)&keygenTag,
        (WebCore::QualifiedName*)&labelTag,
        (WebCore::QualifiedName*)&layerTag,
        (WebCore::QualifiedName*)&legendTag,
        (WebCore::QualifiedName*)&liTag,
        (WebCore::QualifiedName*)&linkTag,
        (WebCore::QualifiedName*)&listingTag,
        (WebCore::QualifiedName*)&mapTag,
        (WebCore::QualifiedName*)&marqueeTag,
        (WebCore::QualifiedName*)&menuTag,
        (WebCore::QualifiedName*)&metaTag,
        (WebCore::QualifiedName*)&nobrTag,
        (WebCore::QualifiedName*)&noembedTag,
        (WebCore::QualifiedName*)&noframesTag,
        (WebCore::QualifiedName*)&nolayerTag,
        (WebCore::QualifiedName*)&noscriptTag,
        (WebCore::QualifiedName*)&objectTag,
        (WebCore::QualifiedName*)&olTag,
        (WebCore::QualifiedName*)&optgroupTag,
        (WebCore::QualifiedName*)&optionTag,
        (WebCore::QualifiedName*)&pTag,
        (WebCore::QualifiedName*)&paramTag,
        (WebCore::QualifiedName*)&plaintextTag,
        (WebCore::QualifiedName*)&preTag,
        (WebCore::QualifiedName*)&qTag,
        (WebCore::QualifiedName*)&sTag,
        (WebCore::QualifiedName*)&sampTag,
        (WebCore::QualifiedName*)&scriptTag,
        (WebCore::QualifiedName*)&selectTag,
        (WebCore::QualifiedName*)&smallTag,
        (WebCore::QualifiedName*)&spanTag,
        (WebCore::QualifiedName*)&strikeTag,
        (WebCore::QualifiedName*)&strongTag,
        (WebCore::QualifiedName*)&styleTag,
        (WebCore::QualifiedName*)&subTag,
        (WebCore::QualifiedName*)&supTag,
        (WebCore::QualifiedName*)&tableTag,
        (WebCore::QualifiedName*)&tbodyTag,
        (WebCore::QualifiedName*)&tdTag,
        (WebCore::QualifiedName*)&textareaTag,
        (WebCore::QualifiedName*)&tfootTag,
        (WebCore::QualifiedName*)&thTag,
        (WebCore::QualifiedName*)&theadTag,
        (WebCore::QualifiedName*)&titleTag,
        (WebCore::QualifiedName*)&trTag,
        (WebCore::QualifiedName*)&ttTag,
        (WebCore::QualifiedName*)&uTag,
        (WebCore::QualifiedName*)&ulTag,
        (WebCore::QualifiedName*)&varTag,
        (WebCore::QualifiedName*)&wbrTag,
        (WebCore::QualifiedName*)&xmpTag,
    };
    *size = 105;
    return HTMLTags;
}

// Attributes
DEFINE_GLOBAL(QualifiedName, abbrAttr, nullAtom, "abbr", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, accept_charsetAttr, nullAtom, "accept_charset", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, acceptAttr, nullAtom, "accept", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, accesskeyAttr, nullAtom, "accesskey", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, actionAttr, nullAtom, "action", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, alignAttr, nullAtom, "align", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, alinkAttr, nullAtom, "alink", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, altAttr, nullAtom, "alt", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, archiveAttr, nullAtom, "archive", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, autocompleteAttr, nullAtom, "autocomplete", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, autosaveAttr, nullAtom, "autosave", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, axisAttr, nullAtom, "axis", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, backgroundAttr, nullAtom, "background", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, behaviorAttr, nullAtom, "behavior", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, bgcolorAttr, nullAtom, "bgcolor", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, bgpropertiesAttr, nullAtom, "bgproperties", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, borderAttr, nullAtom, "border", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, bordercolorAttr, nullAtom, "bordercolor", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, cellpaddingAttr, nullAtom, "cellpadding", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, cellspacingAttr, nullAtom, "cellspacing", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, charAttr, nullAtom, "char", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, challengeAttr, nullAtom, "challenge", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, charoffAttr, nullAtom, "charoff", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, charsetAttr, nullAtom, "charset", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, checkedAttr, nullAtom, "checked", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, cellborderAttr, nullAtom, "cellborder", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, citeAttr, nullAtom, "cite", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, classAttr, nullAtom, "class", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, classidAttr, nullAtom, "classid", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, clearAttr, nullAtom, "clear", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, codeAttr, nullAtom, "code", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, codebaseAttr, nullAtom, "codebase", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, codetypeAttr, nullAtom, "codetype", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, colorAttr, nullAtom, "color", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, colsAttr, nullAtom, "cols", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, colspanAttr, nullAtom, "colspan", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, compactAttr, nullAtom, "compact", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, compositeAttr, nullAtom, "composite", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, contentAttr, nullAtom, "content", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, contenteditableAttr, nullAtom, "contenteditable", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, coordsAttr, nullAtom, "coords", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, ctiAttr, nullAtom, "cti", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, dataAttr, nullAtom, "data", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, datetimeAttr, nullAtom, "datetime", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, declareAttr, nullAtom, "declare", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, deferAttr, nullAtom, "defer", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, dirAttr, nullAtom, "dir", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, directionAttr, nullAtom, "direction", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, directkeyAttr, nullAtom, "directkey", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, disabledAttr, nullAtom, "disabled", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, emailAttr, nullAtom, "email", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, enctypeAttr, nullAtom, "enctype", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, faceAttr, nullAtom, "face", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, forAttr, nullAtom, "for", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, frameAttr, nullAtom, "frame", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, frameborderAttr, nullAtom, "frameborder", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, headersAttr, nullAtom, "headers", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, heightAttr, nullAtom, "height", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, hiddenAttr, nullAtom, "hidden", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, hrefAttr, nullAtom, "href", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, hreflangAttr, nullAtom, "hreflang", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, hspaceAttr, nullAtom, "hspace", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, http_equivAttr, nullAtom, "http_equiv", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, idAttr, nullAtom, "id", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, incrementalAttr, nullAtom, "incremental", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, ismapAttr, nullAtom, "ismap", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, keytypeAttr, nullAtom, "keytype", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, labelAttr, nullAtom, "label", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, langAttr, nullAtom, "lang", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, languageAttr, nullAtom, "language", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, leftAttr, nullAtom, "left", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, leftmarginAttr, nullAtom, "leftmargin", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, linkAttr, nullAtom, "link", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, longdescAttr, nullAtom, "longdesc", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, loopAttr, nullAtom, "loop", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, lowsrcAttr, nullAtom, "lowsrc", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, marginheightAttr, nullAtom, "marginheight", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, marginwidthAttr, nullAtom, "marginwidth", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, maxAttr, nullAtom, "max", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, maxlengthAttr, nullAtom, "maxlength", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, mayscriptAttr, nullAtom, "mayscript", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, mediaAttr, nullAtom, "media", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, methodAttr, nullAtom, "method", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, minAttr, nullAtom, "min", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, multipleAttr, nullAtom, "multiple", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, nameAttr, nullAtom, "name", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, nohrefAttr, nullAtom, "nohref", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, noresizeAttr, nullAtom, "noresize", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, noshadeAttr, nullAtom, "noshade", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, nowrapAttr, nullAtom, "nowrap", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, objectAttr, nullAtom, "object", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, onabortAttr, nullAtom, "onabort", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, onbeforecopyAttr, nullAtom, "onbeforecopy", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, onbeforecutAttr, nullAtom, "onbeforecut", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, onbeforepasteAttr, nullAtom, "onbeforepaste", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, onbeforeunloadAttr, nullAtom, "onbeforeunload", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, onblurAttr, nullAtom, "onblur", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, onchangeAttr, nullAtom, "onchange", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, onclickAttr, nullAtom, "onclick", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, oncontextmenuAttr, nullAtom, "oncontextmenu", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, oncopyAttr, nullAtom, "oncopy", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, oncutAttr, nullAtom, "oncut", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, ondblclickAttr, nullAtom, "ondblclick", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, ondragAttr, nullAtom, "ondrag", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, ondragendAttr, nullAtom, "ondragend", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, ondragenterAttr, nullAtom, "ondragenter", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, ondragleaveAttr, nullAtom, "ondragleave", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, ondragoverAttr, nullAtom, "ondragover", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, ondragstartAttr, nullAtom, "ondragstart", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, ondropAttr, nullAtom, "ondrop", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, onerrorAttr, nullAtom, "onerror", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, onfocusAttr, nullAtom, "onfocus", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, oninputAttr, nullAtom, "oninput", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, onkeydownAttr, nullAtom, "onkeydown", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, onkeypressAttr, nullAtom, "onkeypress", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, onkeyupAttr, nullAtom, "onkeyup", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, onloadAttr, nullAtom, "onload", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, onmousedownAttr, nullAtom, "onmousedown", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, onmousemoveAttr, nullAtom, "onmousemove", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, onmouseoutAttr, nullAtom, "onmouseout", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, onmouseoverAttr, nullAtom, "onmouseover", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, onmouseupAttr, nullAtom, "onmouseup", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, onmousewheelAttr, nullAtom, "onmousewheel", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, onpasteAttr, nullAtom, "onpaste", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, onresetAttr, nullAtom, "onreset", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, onresizeAttr, nullAtom, "onresize", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, onscrollAttr, nullAtom, "onscroll", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, onsearchAttr, nullAtom, "onsearch", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, onselectAttr, nullAtom, "onselect", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, onselectstartAttr, nullAtom, "onselectstart", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, onsubmitAttr, nullAtom, "onsubmit", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, onunloadAttr, nullAtom, "onunload", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, pagexAttr, nullAtom, "pagex", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, pageyAttr, nullAtom, "pagey", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, placeholderAttr, nullAtom, "placeholder", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, plainAttr, nullAtom, "plain", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, pluginpageAttr, nullAtom, "pluginpage", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, pluginspageAttr, nullAtom, "pluginspage", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, pluginurlAttr, nullAtom, "pluginurl", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, precisionAttr, nullAtom, "precision", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, profileAttr, nullAtom, "profile", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, promptAttr, nullAtom, "prompt", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, readonlyAttr, nullAtom, "readonly", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, relAttr, nullAtom, "rel", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, resultsAttr, nullAtom, "results", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, revAttr, nullAtom, "rev", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, rowsAttr, nullAtom, "rows", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, rowspanAttr, nullAtom, "rowspan", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, rulesAttr, nullAtom, "rules", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, schemeAttr, nullAtom, "scheme", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, scopeAttr, nullAtom, "scope", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, scrollamountAttr, nullAtom, "scrollamount", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, scrolldelayAttr, nullAtom, "scrolldelay", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, scrollingAttr, nullAtom, "scrolling", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, selectedAttr, nullAtom, "selected", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, shapeAttr, nullAtom, "shape", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, sizeAttr, nullAtom, "size", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, soundstartAttr, nullAtom, "soundstart", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, spanAttr, nullAtom, "span", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, srcAttr, nullAtom, "src", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, standbyAttr, nullAtom, "standby", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, startAttr, nullAtom, "start", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, styleAttr, nullAtom, "style", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, summaryAttr, nullAtom, "summary", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, tabindexAttr, nullAtom, "tabindex", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, tableborderAttr, nullAtom, "tableborder", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, targetAttr, nullAtom, "target", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, telbookAttr, nullAtom, "telbook", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, textAttr, nullAtom, "text", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, titleAttr, nullAtom, "title", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, topAttr, nullAtom, "top", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, topmarginAttr, nullAtom, "topmargin", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, truespeedAttr, nullAtom, "truespeed", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, typeAttr, nullAtom, "type", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, usemapAttr, nullAtom, "usemap", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, valignAttr, nullAtom, "valign", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, valueAttr, nullAtom, "value", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, valuetypeAttr, nullAtom, "valuetype", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, versionAttr, nullAtom, "version", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, viewsourceAttr, nullAtom, "viewsource", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, vlinkAttr, nullAtom, "vlink", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, volumeAttr, nullAtom, "volume", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, vspaceAttr, nullAtom, "vspace", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, widthAttr, nullAtom, "width", xhtmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, wrapAttr, nullAtom, "wrap", xhtmlNamespaceURI);


WebCore::QualifiedName** getHTMLAttrs(size_t* size)
{
    static WebCore::QualifiedName* HTMLAttr[] = {
        (WebCore::QualifiedName*)&abbrAttr,
        (WebCore::QualifiedName*)&accept_charsetAttr,
        (WebCore::QualifiedName*)&acceptAttr,
        (WebCore::QualifiedName*)&accesskeyAttr,
        (WebCore::QualifiedName*)&actionAttr,
        (WebCore::QualifiedName*)&alignAttr,
        (WebCore::QualifiedName*)&alinkAttr,
        (WebCore::QualifiedName*)&altAttr,
        (WebCore::QualifiedName*)&archiveAttr,
        (WebCore::QualifiedName*)&autocompleteAttr,
        (WebCore::QualifiedName*)&autosaveAttr,
        (WebCore::QualifiedName*)&axisAttr,
        (WebCore::QualifiedName*)&backgroundAttr,
        (WebCore::QualifiedName*)&behaviorAttr,
        (WebCore::QualifiedName*)&bgcolorAttr,
        (WebCore::QualifiedName*)&bgpropertiesAttr,
        (WebCore::QualifiedName*)&borderAttr,
        (WebCore::QualifiedName*)&bordercolorAttr,
        (WebCore::QualifiedName*)&cellpaddingAttr,
        (WebCore::QualifiedName*)&cellspacingAttr,
        (WebCore::QualifiedName*)&charAttr,
        (WebCore::QualifiedName*)&challengeAttr,
        (WebCore::QualifiedName*)&charoffAttr,
        (WebCore::QualifiedName*)&charsetAttr,
        (WebCore::QualifiedName*)&checkedAttr,
        (WebCore::QualifiedName*)&cellborderAttr,
        (WebCore::QualifiedName*)&citeAttr,
        (WebCore::QualifiedName*)&classAttr,
        (WebCore::QualifiedName*)&classidAttr,
        (WebCore::QualifiedName*)&clearAttr,
        (WebCore::QualifiedName*)&codeAttr,
        (WebCore::QualifiedName*)&codebaseAttr,
        (WebCore::QualifiedName*)&codetypeAttr,
        (WebCore::QualifiedName*)&colorAttr,
        (WebCore::QualifiedName*)&colsAttr,
        (WebCore::QualifiedName*)&colspanAttr,
        (WebCore::QualifiedName*)&compactAttr,
        (WebCore::QualifiedName*)&compositeAttr,
        (WebCore::QualifiedName*)&contentAttr,
        (WebCore::QualifiedName*)&contenteditableAttr,
        (WebCore::QualifiedName*)&coordsAttr,
        (WebCore::QualifiedName*)&ctiAttr,
        (WebCore::QualifiedName*)&dataAttr,
        (WebCore::QualifiedName*)&datetimeAttr,
        (WebCore::QualifiedName*)&declareAttr,
        (WebCore::QualifiedName*)&deferAttr,
        (WebCore::QualifiedName*)&dirAttr,
        (WebCore::QualifiedName*)&directionAttr,
        (WebCore::QualifiedName*)&directkeyAttr,
        (WebCore::QualifiedName*)&disabledAttr,
        (WebCore::QualifiedName*)&emailAttr,
        (WebCore::QualifiedName*)&enctypeAttr,
        (WebCore::QualifiedName*)&faceAttr,
        (WebCore::QualifiedName*)&forAttr,
        (WebCore::QualifiedName*)&frameAttr,
        (WebCore::QualifiedName*)&frameborderAttr,
        (WebCore::QualifiedName*)&headersAttr,
        (WebCore::QualifiedName*)&heightAttr,
        (WebCore::QualifiedName*)&hiddenAttr,
        (WebCore::QualifiedName*)&hrefAttr,
        (WebCore::QualifiedName*)&hreflangAttr,
        (WebCore::QualifiedName*)&hspaceAttr,
        (WebCore::QualifiedName*)&http_equivAttr,
        (WebCore::QualifiedName*)&idAttr,
        (WebCore::QualifiedName*)&incrementalAttr,
        (WebCore::QualifiedName*)&ismapAttr,
        (WebCore::QualifiedName*)&keytypeAttr,
        (WebCore::QualifiedName*)&labelAttr,
        (WebCore::QualifiedName*)&langAttr,
        (WebCore::QualifiedName*)&languageAttr,
        (WebCore::QualifiedName*)&leftAttr,
        (WebCore::QualifiedName*)&leftmarginAttr,
        (WebCore::QualifiedName*)&linkAttr,
        (WebCore::QualifiedName*)&longdescAttr,
        (WebCore::QualifiedName*)&loopAttr,
        (WebCore::QualifiedName*)&lowsrcAttr,
        (WebCore::QualifiedName*)&marginheightAttr,
        (WebCore::QualifiedName*)&marginwidthAttr,
        (WebCore::QualifiedName*)&maxAttr,
        (WebCore::QualifiedName*)&maxlengthAttr,
        (WebCore::QualifiedName*)&mayscriptAttr,
        (WebCore::QualifiedName*)&mediaAttr,
        (WebCore::QualifiedName*)&methodAttr,
        (WebCore::QualifiedName*)&minAttr,
        (WebCore::QualifiedName*)&multipleAttr,
        (WebCore::QualifiedName*)&nameAttr,
        (WebCore::QualifiedName*)&nohrefAttr,
        (WebCore::QualifiedName*)&noresizeAttr,
        (WebCore::QualifiedName*)&noshadeAttr,
        (WebCore::QualifiedName*)&nowrapAttr,
        (WebCore::QualifiedName*)&objectAttr,
        (WebCore::QualifiedName*)&onabortAttr,
        (WebCore::QualifiedName*)&onbeforecopyAttr,
        (WebCore::QualifiedName*)&onbeforecutAttr,
        (WebCore::QualifiedName*)&onbeforepasteAttr,
        (WebCore::QualifiedName*)&onbeforeunloadAttr,
        (WebCore::QualifiedName*)&onblurAttr,
        (WebCore::QualifiedName*)&onchangeAttr,
        (WebCore::QualifiedName*)&onclickAttr,
        (WebCore::QualifiedName*)&oncontextmenuAttr,
        (WebCore::QualifiedName*)&oncopyAttr,
        (WebCore::QualifiedName*)&oncutAttr,
        (WebCore::QualifiedName*)&ondblclickAttr,
        (WebCore::QualifiedName*)&ondragAttr,
        (WebCore::QualifiedName*)&ondragendAttr,
        (WebCore::QualifiedName*)&ondragenterAttr,
        (WebCore::QualifiedName*)&ondragleaveAttr,
        (WebCore::QualifiedName*)&ondragoverAttr,
        (WebCore::QualifiedName*)&ondragstartAttr,
        (WebCore::QualifiedName*)&ondropAttr,
        (WebCore::QualifiedName*)&onerrorAttr,
        (WebCore::QualifiedName*)&onfocusAttr,
        (WebCore::QualifiedName*)&oninputAttr,
        (WebCore::QualifiedName*)&onkeydownAttr,
        (WebCore::QualifiedName*)&onkeypressAttr,
        (WebCore::QualifiedName*)&onkeyupAttr,
        (WebCore::QualifiedName*)&onloadAttr,
        (WebCore::QualifiedName*)&onmousedownAttr,
        (WebCore::QualifiedName*)&onmousemoveAttr,
        (WebCore::QualifiedName*)&onmouseoutAttr,
        (WebCore::QualifiedName*)&onmouseoverAttr,
        (WebCore::QualifiedName*)&onmouseupAttr,
        (WebCore::QualifiedName*)&onmousewheelAttr,
        (WebCore::QualifiedName*)&onpasteAttr,
        (WebCore::QualifiedName*)&onresetAttr,
        (WebCore::QualifiedName*)&onresizeAttr,
        (WebCore::QualifiedName*)&onscrollAttr,
        (WebCore::QualifiedName*)&onsearchAttr,
        (WebCore::QualifiedName*)&onselectAttr,
        (WebCore::QualifiedName*)&onselectstartAttr,
        (WebCore::QualifiedName*)&onsubmitAttr,
        (WebCore::QualifiedName*)&onunloadAttr,
        (WebCore::QualifiedName*)&pagexAttr,
        (WebCore::QualifiedName*)&pageyAttr,
        (WebCore::QualifiedName*)&placeholderAttr,
        (WebCore::QualifiedName*)&plainAttr,
        (WebCore::QualifiedName*)&pluginpageAttr,
        (WebCore::QualifiedName*)&pluginspageAttr,
        (WebCore::QualifiedName*)&pluginurlAttr,
        (WebCore::QualifiedName*)&precisionAttr,
        (WebCore::QualifiedName*)&profileAttr,
        (WebCore::QualifiedName*)&promptAttr,
        (WebCore::QualifiedName*)&readonlyAttr,
        (WebCore::QualifiedName*)&relAttr,
        (WebCore::QualifiedName*)&resultsAttr,
        (WebCore::QualifiedName*)&revAttr,
        (WebCore::QualifiedName*)&rowsAttr,
        (WebCore::QualifiedName*)&rowspanAttr,
        (WebCore::QualifiedName*)&rulesAttr,
        (WebCore::QualifiedName*)&schemeAttr,
        (WebCore::QualifiedName*)&scopeAttr,
        (WebCore::QualifiedName*)&scrollamountAttr,
        (WebCore::QualifiedName*)&scrolldelayAttr,
        (WebCore::QualifiedName*)&scrollingAttr,
        (WebCore::QualifiedName*)&selectedAttr,
        (WebCore::QualifiedName*)&shapeAttr,
        (WebCore::QualifiedName*)&sizeAttr,
        (WebCore::QualifiedName*)&soundstartAttr,
        (WebCore::QualifiedName*)&spanAttr,
        (WebCore::QualifiedName*)&srcAttr,
        (WebCore::QualifiedName*)&standbyAttr,
        (WebCore::QualifiedName*)&startAttr,
        (WebCore::QualifiedName*)&styleAttr,
        (WebCore::QualifiedName*)&summaryAttr,
        (WebCore::QualifiedName*)&tabindexAttr,
        (WebCore::QualifiedName*)&tableborderAttr,
        (WebCore::QualifiedName*)&targetAttr,
        (WebCore::QualifiedName*)&telbookAttr,
        (WebCore::QualifiedName*)&textAttr,
        (WebCore::QualifiedName*)&titleAttr,
        (WebCore::QualifiedName*)&topAttr,
        (WebCore::QualifiedName*)&topmarginAttr,
        (WebCore::QualifiedName*)&truespeedAttr,
        (WebCore::QualifiedName*)&typeAttr,
        (WebCore::QualifiedName*)&usemapAttr,
        (WebCore::QualifiedName*)&valignAttr,
        (WebCore::QualifiedName*)&valueAttr,
        (WebCore::QualifiedName*)&valuetypeAttr,
        (WebCore::QualifiedName*)&versionAttr,
        (WebCore::QualifiedName*)&viewsourceAttr,
        (WebCore::QualifiedName*)&vlinkAttr,
        (WebCore::QualifiedName*)&volumeAttr,
        (WebCore::QualifiedName*)&vspaceAttr,
        (WebCore::QualifiedName*)&widthAttr,
        (WebCore::QualifiedName*)&wrapAttr,
    };
    *size = 185;
    return HTMLAttr;
}

void init()
{
    if (initialized)
        return;
    initialized = true;
    
    // Use placement new to initialize the globals.
    
    AtomicString::init();
    AtomicString xhtmlNS(xhtmlNSString);

    // Namespace
    new ((void*)&xhtmlNamespaceURI) AtomicString(xhtmlNS);
    new ((void*)&aTag) QualifiedName(nullAtom, aTagString, xhtmlNS);
    new ((void*)&abbrTag) QualifiedName(nullAtom, abbrTagString, xhtmlNS);
    new ((void*)&acronymTag) QualifiedName(nullAtom, acronymTagString, xhtmlNS);
    new ((void*)&addressTag) QualifiedName(nullAtom, addressTagString, xhtmlNS);
    new ((void*)&appletTag) QualifiedName(nullAtom, appletTagString, xhtmlNS);
    new ((void*)&areaTag) QualifiedName(nullAtom, areaTagString, xhtmlNS);
    new ((void*)&bTag) QualifiedName(nullAtom, bTagString, xhtmlNS);
    new ((void*)&baseTag) QualifiedName(nullAtom, baseTagString, xhtmlNS);
    new ((void*)&basefontTag) QualifiedName(nullAtom, basefontTagString, xhtmlNS);
    new ((void*)&bdoTag) QualifiedName(nullAtom, bdoTagString, xhtmlNS);
    new ((void*)&bgsoundTag) QualifiedName(nullAtom, bgsoundTagString, xhtmlNS);
    new ((void*)&bigTag) QualifiedName(nullAtom, bigTagString, xhtmlNS);
    new ((void*)&blockquoteTag) QualifiedName(nullAtom, blockquoteTagString, xhtmlNS);
    new ((void*)&bodyTag) QualifiedName(nullAtom, bodyTagString, xhtmlNS);
    new ((void*)&brTag) QualifiedName(nullAtom, brTagString, xhtmlNS);
    new ((void*)&buttonTag) QualifiedName(nullAtom, buttonTagString, xhtmlNS);
    new ((void*)&canvasTag) QualifiedName(nullAtom, canvasTagString, xhtmlNS);
    new ((void*)&captionTag) QualifiedName(nullAtom, captionTagString, xhtmlNS);
    new ((void*)&centerTag) QualifiedName(nullAtom, centerTagString, xhtmlNS);
    new ((void*)&citeTag) QualifiedName(nullAtom, citeTagString, xhtmlNS);
    new ((void*)&codeTag) QualifiedName(nullAtom, codeTagString, xhtmlNS);
    new ((void*)&colTag) QualifiedName(nullAtom, colTagString, xhtmlNS);
    new ((void*)&colgroupTag) QualifiedName(nullAtom, colgroupTagString, xhtmlNS);
    new ((void*)&ddTag) QualifiedName(nullAtom, ddTagString, xhtmlNS);
    new ((void*)&delTag) QualifiedName(nullAtom, delTagString, xhtmlNS);
    new ((void*)&dfnTag) QualifiedName(nullAtom, dfnTagString, xhtmlNS);
    new ((void*)&dirTag) QualifiedName(nullAtom, dirTagString, xhtmlNS);
    new ((void*)&divTag) QualifiedName(nullAtom, divTagString, xhtmlNS);
    new ((void*)&dlTag) QualifiedName(nullAtom, dlTagString, xhtmlNS);
    new ((void*)&dtTag) QualifiedName(nullAtom, dtTagString, xhtmlNS);
    new ((void*)&emTag) QualifiedName(nullAtom, emTagString, xhtmlNS);
    new ((void*)&embedTag) QualifiedName(nullAtom, embedTagString, xhtmlNS);
    new ((void*)&fieldsetTag) QualifiedName(nullAtom, fieldsetTagString, xhtmlNS);
    new ((void*)&fontTag) QualifiedName(nullAtom, fontTagString, xhtmlNS);
    new ((void*)&formTag) QualifiedName(nullAtom, formTagString, xhtmlNS);
    new ((void*)&frameTag) QualifiedName(nullAtom, frameTagString, xhtmlNS);
    new ((void*)&framesetTag) QualifiedName(nullAtom, framesetTagString, xhtmlNS);
    new ((void*)&headTag) QualifiedName(nullAtom, headTagString, xhtmlNS);
    new ((void*)&h1Tag) QualifiedName(nullAtom, h1TagString, xhtmlNS);
    new ((void*)&h2Tag) QualifiedName(nullAtom, h2TagString, xhtmlNS);
    new ((void*)&h3Tag) QualifiedName(nullAtom, h3TagString, xhtmlNS);
    new ((void*)&h4Tag) QualifiedName(nullAtom, h4TagString, xhtmlNS);
    new ((void*)&h5Tag) QualifiedName(nullAtom, h5TagString, xhtmlNS);
    new ((void*)&h6Tag) QualifiedName(nullAtom, h6TagString, xhtmlNS);
    new ((void*)&hrTag) QualifiedName(nullAtom, hrTagString, xhtmlNS);
    new ((void*)&htmlTag) QualifiedName(nullAtom, htmlTagString, xhtmlNS);
    new ((void*)&iTag) QualifiedName(nullAtom, iTagString, xhtmlNS);
    new ((void*)&iframeTag) QualifiedName(nullAtom, iframeTagString, xhtmlNS);
    new ((void*)&imageTag) QualifiedName(nullAtom, imageTagString, xhtmlNS);
    new ((void*)&imgTag) QualifiedName(nullAtom, imgTagString, xhtmlNS);
    new ((void*)&inputTag) QualifiedName(nullAtom, inputTagString, xhtmlNS);
    new ((void*)&insTag) QualifiedName(nullAtom, insTagString, xhtmlNS);
    new ((void*)&isindexTag) QualifiedName(nullAtom, isindexTagString, xhtmlNS);
    new ((void*)&kbdTag) QualifiedName(nullAtom, kbdTagString, xhtmlNS);
    new ((void*)&keygenTag) QualifiedName(nullAtom, keygenTagString, xhtmlNS);
    new ((void*)&labelTag) QualifiedName(nullAtom, labelTagString, xhtmlNS);
    new ((void*)&layerTag) QualifiedName(nullAtom, layerTagString, xhtmlNS);
    new ((void*)&legendTag) QualifiedName(nullAtom, legendTagString, xhtmlNS);
    new ((void*)&liTag) QualifiedName(nullAtom, liTagString, xhtmlNS);
    new ((void*)&linkTag) QualifiedName(nullAtom, linkTagString, xhtmlNS);
    new ((void*)&listingTag) QualifiedName(nullAtom, listingTagString, xhtmlNS);
    new ((void*)&mapTag) QualifiedName(nullAtom, mapTagString, xhtmlNS);
    new ((void*)&marqueeTag) QualifiedName(nullAtom, marqueeTagString, xhtmlNS);
    new ((void*)&menuTag) QualifiedName(nullAtom, menuTagString, xhtmlNS);
    new ((void*)&metaTag) QualifiedName(nullAtom, metaTagString, xhtmlNS);
    new ((void*)&nobrTag) QualifiedName(nullAtom, nobrTagString, xhtmlNS);
    new ((void*)&noembedTag) QualifiedName(nullAtom, noembedTagString, xhtmlNS);
    new ((void*)&noframesTag) QualifiedName(nullAtom, noframesTagString, xhtmlNS);
    new ((void*)&nolayerTag) QualifiedName(nullAtom, nolayerTagString, xhtmlNS);
    new ((void*)&noscriptTag) QualifiedName(nullAtom, noscriptTagString, xhtmlNS);
    new ((void*)&objectTag) QualifiedName(nullAtom, objectTagString, xhtmlNS);
    new ((void*)&olTag) QualifiedName(nullAtom, olTagString, xhtmlNS);
    new ((void*)&optgroupTag) QualifiedName(nullAtom, optgroupTagString, xhtmlNS);
    new ((void*)&optionTag) QualifiedName(nullAtom, optionTagString, xhtmlNS);
    new ((void*)&pTag) QualifiedName(nullAtom, pTagString, xhtmlNS);
    new ((void*)&paramTag) QualifiedName(nullAtom, paramTagString, xhtmlNS);
    new ((void*)&plaintextTag) QualifiedName(nullAtom, plaintextTagString, xhtmlNS);
    new ((void*)&preTag) QualifiedName(nullAtom, preTagString, xhtmlNS);
    new ((void*)&qTag) QualifiedName(nullAtom, qTagString, xhtmlNS);
    new ((void*)&sTag) QualifiedName(nullAtom, sTagString, xhtmlNS);
    new ((void*)&sampTag) QualifiedName(nullAtom, sampTagString, xhtmlNS);
    new ((void*)&scriptTag) QualifiedName(nullAtom, scriptTagString, xhtmlNS);
    new ((void*)&selectTag) QualifiedName(nullAtom, selectTagString, xhtmlNS);
    new ((void*)&smallTag) QualifiedName(nullAtom, smallTagString, xhtmlNS);
    new ((void*)&spanTag) QualifiedName(nullAtom, spanTagString, xhtmlNS);
    new ((void*)&strikeTag) QualifiedName(nullAtom, strikeTagString, xhtmlNS);
    new ((void*)&strongTag) QualifiedName(nullAtom, strongTagString, xhtmlNS);
    new ((void*)&styleTag) QualifiedName(nullAtom, styleTagString, xhtmlNS);
    new ((void*)&subTag) QualifiedName(nullAtom, subTagString, xhtmlNS);
    new ((void*)&supTag) QualifiedName(nullAtom, supTagString, xhtmlNS);
    new ((void*)&tableTag) QualifiedName(nullAtom, tableTagString, xhtmlNS);
    new ((void*)&tbodyTag) QualifiedName(nullAtom, tbodyTagString, xhtmlNS);
    new ((void*)&tdTag) QualifiedName(nullAtom, tdTagString, xhtmlNS);
    new ((void*)&textareaTag) QualifiedName(nullAtom, textareaTagString, xhtmlNS);
    new ((void*)&tfootTag) QualifiedName(nullAtom, tfootTagString, xhtmlNS);
    new ((void*)&thTag) QualifiedName(nullAtom, thTagString, xhtmlNS);
    new ((void*)&theadTag) QualifiedName(nullAtom, theadTagString, xhtmlNS);
    new ((void*)&titleTag) QualifiedName(nullAtom, titleTagString, xhtmlNS);
    new ((void*)&trTag) QualifiedName(nullAtom, trTagString, xhtmlNS);
    new ((void*)&ttTag) QualifiedName(nullAtom, ttTagString, xhtmlNS);
    new ((void*)&uTag) QualifiedName(nullAtom, uTagString, xhtmlNS);
    new ((void*)&ulTag) QualifiedName(nullAtom, ulTagString, xhtmlNS);
    new ((void*)&varTag) QualifiedName(nullAtom, varTagString, xhtmlNS);
    new ((void*)&wbrTag) QualifiedName(nullAtom, wbrTagString, xhtmlNS);
    new ((void*)&xmpTag) QualifiedName(nullAtom, xmpTagString, xhtmlNS);

    accept_charsetAttrString = "accept-charset";
    http_equivAttrString = "http-equiv";

    new ((void*)&abbrAttr) QualifiedName(nullAtom, abbrAttrString, nullAtom);
    new ((void*)&accept_charsetAttr) QualifiedName(nullAtom, accept_charsetAttrString, nullAtom);
    new ((void*)&acceptAttr) QualifiedName(nullAtom, acceptAttrString, nullAtom);
    new ((void*)&accesskeyAttr) QualifiedName(nullAtom, accesskeyAttrString, nullAtom);
    new ((void*)&actionAttr) QualifiedName(nullAtom, actionAttrString, nullAtom);
    new ((void*)&alignAttr) QualifiedName(nullAtom, alignAttrString, nullAtom);
    new ((void*)&alinkAttr) QualifiedName(nullAtom, alinkAttrString, nullAtom);
    new ((void*)&altAttr) QualifiedName(nullAtom, altAttrString, nullAtom);
    new ((void*)&archiveAttr) QualifiedName(nullAtom, archiveAttrString, nullAtom);
    new ((void*)&autocompleteAttr) QualifiedName(nullAtom, autocompleteAttrString, nullAtom);
    new ((void*)&autosaveAttr) QualifiedName(nullAtom, autosaveAttrString, nullAtom);
    new ((void*)&axisAttr) QualifiedName(nullAtom, axisAttrString, nullAtom);
    new ((void*)&backgroundAttr) QualifiedName(nullAtom, backgroundAttrString, nullAtom);
    new ((void*)&behaviorAttr) QualifiedName(nullAtom, behaviorAttrString, nullAtom);
    new ((void*)&bgcolorAttr) QualifiedName(nullAtom, bgcolorAttrString, nullAtom);
    new ((void*)&bgpropertiesAttr) QualifiedName(nullAtom, bgpropertiesAttrString, nullAtom);
    new ((void*)&borderAttr) QualifiedName(nullAtom, borderAttrString, nullAtom);
    new ((void*)&bordercolorAttr) QualifiedName(nullAtom, bordercolorAttrString, nullAtom);
    new ((void*)&cellpaddingAttr) QualifiedName(nullAtom, cellpaddingAttrString, nullAtom);
    new ((void*)&cellspacingAttr) QualifiedName(nullAtom, cellspacingAttrString, nullAtom);
    new ((void*)&charAttr) QualifiedName(nullAtom, charAttrString, nullAtom);
    new ((void*)&challengeAttr) QualifiedName(nullAtom, challengeAttrString, nullAtom);
    new ((void*)&charoffAttr) QualifiedName(nullAtom, charoffAttrString, nullAtom);
    new ((void*)&charsetAttr) QualifiedName(nullAtom, charsetAttrString, nullAtom);
    new ((void*)&checkedAttr) QualifiedName(nullAtom, checkedAttrString, nullAtom);
    new ((void*)&cellborderAttr) QualifiedName(nullAtom, cellborderAttrString, nullAtom);
    new ((void*)&citeAttr) QualifiedName(nullAtom, citeAttrString, nullAtom);
    new ((void*)&classAttr) QualifiedName(nullAtom, classAttrString, nullAtom);
    new ((void*)&classidAttr) QualifiedName(nullAtom, classidAttrString, nullAtom);
    new ((void*)&clearAttr) QualifiedName(nullAtom, clearAttrString, nullAtom);
    new ((void*)&codeAttr) QualifiedName(nullAtom, codeAttrString, nullAtom);
    new ((void*)&codebaseAttr) QualifiedName(nullAtom, codebaseAttrString, nullAtom);
    new ((void*)&codetypeAttr) QualifiedName(nullAtom, codetypeAttrString, nullAtom);
    new ((void*)&colorAttr) QualifiedName(nullAtom, colorAttrString, nullAtom);
    new ((void*)&colsAttr) QualifiedName(nullAtom, colsAttrString, nullAtom);
    new ((void*)&colspanAttr) QualifiedName(nullAtom, colspanAttrString, nullAtom);
    new ((void*)&compactAttr) QualifiedName(nullAtom, compactAttrString, nullAtom);
    new ((void*)&compositeAttr) QualifiedName(nullAtom, compositeAttrString, nullAtom);
    new ((void*)&contentAttr) QualifiedName(nullAtom, contentAttrString, nullAtom);
    new ((void*)&contenteditableAttr) QualifiedName(nullAtom, contenteditableAttrString, nullAtom);
    new ((void*)&coordsAttr) QualifiedName(nullAtom, coordsAttrString, nullAtom);
    new ((void*)&ctiAttr) QualifiedName(nullAtom, ctiAttrString, nullAtom);
    new ((void*)&dataAttr) QualifiedName(nullAtom, dataAttrString, nullAtom);
    new ((void*)&datetimeAttr) QualifiedName(nullAtom, datetimeAttrString, nullAtom);
    new ((void*)&declareAttr) QualifiedName(nullAtom, declareAttrString, nullAtom);
    new ((void*)&deferAttr) QualifiedName(nullAtom, deferAttrString, nullAtom);
    new ((void*)&dirAttr) QualifiedName(nullAtom, dirAttrString, nullAtom);
    new ((void*)&directionAttr) QualifiedName(nullAtom, directionAttrString, nullAtom);
    new ((void*)&directkeyAttr) QualifiedName(nullAtom, directkeyAttrString, nullAtom);
    new ((void*)&disabledAttr) QualifiedName(nullAtom, disabledAttrString, nullAtom);
    new ((void*)&emailAttr) QualifiedName(nullAtom, emailAttrString, nullAtom);
    new ((void*)&enctypeAttr) QualifiedName(nullAtom, enctypeAttrString, nullAtom);
    new ((void*)&faceAttr) QualifiedName(nullAtom, faceAttrString, nullAtom);
    new ((void*)&forAttr) QualifiedName(nullAtom, forAttrString, nullAtom);
    new ((void*)&frameAttr) QualifiedName(nullAtom, frameAttrString, nullAtom);
    new ((void*)&frameborderAttr) QualifiedName(nullAtom, frameborderAttrString, nullAtom);
    new ((void*)&headersAttr) QualifiedName(nullAtom, headersAttrString, nullAtom);
    new ((void*)&heightAttr) QualifiedName(nullAtom, heightAttrString, nullAtom);
    new ((void*)&hiddenAttr) QualifiedName(nullAtom, hiddenAttrString, nullAtom);
    new ((void*)&hrefAttr) QualifiedName(nullAtom, hrefAttrString, nullAtom);
    new ((void*)&hreflangAttr) QualifiedName(nullAtom, hreflangAttrString, nullAtom);
    new ((void*)&hspaceAttr) QualifiedName(nullAtom, hspaceAttrString, nullAtom);
    new ((void*)&http_equivAttr) QualifiedName(nullAtom, http_equivAttrString, nullAtom);
    new ((void*)&idAttr) QualifiedName(nullAtom, idAttrString, nullAtom);
    new ((void*)&incrementalAttr) QualifiedName(nullAtom, incrementalAttrString, nullAtom);
    new ((void*)&ismapAttr) QualifiedName(nullAtom, ismapAttrString, nullAtom);
    new ((void*)&keytypeAttr) QualifiedName(nullAtom, keytypeAttrString, nullAtom);
    new ((void*)&labelAttr) QualifiedName(nullAtom, labelAttrString, nullAtom);
    new ((void*)&langAttr) QualifiedName(nullAtom, langAttrString, nullAtom);
    new ((void*)&languageAttr) QualifiedName(nullAtom, languageAttrString, nullAtom);
    new ((void*)&leftAttr) QualifiedName(nullAtom, leftAttrString, nullAtom);
    new ((void*)&leftmarginAttr) QualifiedName(nullAtom, leftmarginAttrString, nullAtom);
    new ((void*)&linkAttr) QualifiedName(nullAtom, linkAttrString, nullAtom);
    new ((void*)&longdescAttr) QualifiedName(nullAtom, longdescAttrString, nullAtom);
    new ((void*)&loopAttr) QualifiedName(nullAtom, loopAttrString, nullAtom);
    new ((void*)&lowsrcAttr) QualifiedName(nullAtom, lowsrcAttrString, nullAtom);
    new ((void*)&marginheightAttr) QualifiedName(nullAtom, marginheightAttrString, nullAtom);
    new ((void*)&marginwidthAttr) QualifiedName(nullAtom, marginwidthAttrString, nullAtom);
    new ((void*)&maxAttr) QualifiedName(nullAtom, maxAttrString, nullAtom);
    new ((void*)&maxlengthAttr) QualifiedName(nullAtom, maxlengthAttrString, nullAtom);
    new ((void*)&mayscriptAttr) QualifiedName(nullAtom, mayscriptAttrString, nullAtom);
    new ((void*)&mediaAttr) QualifiedName(nullAtom, mediaAttrString, nullAtom);
    new ((void*)&methodAttr) QualifiedName(nullAtom, methodAttrString, nullAtom);
    new ((void*)&minAttr) QualifiedName(nullAtom, minAttrString, nullAtom);
    new ((void*)&multipleAttr) QualifiedName(nullAtom, multipleAttrString, nullAtom);
    new ((void*)&nameAttr) QualifiedName(nullAtom, nameAttrString, nullAtom);
    new ((void*)&nohrefAttr) QualifiedName(nullAtom, nohrefAttrString, nullAtom);
    new ((void*)&noresizeAttr) QualifiedName(nullAtom, noresizeAttrString, nullAtom);
    new ((void*)&noshadeAttr) QualifiedName(nullAtom, noshadeAttrString, nullAtom);
    new ((void*)&nowrapAttr) QualifiedName(nullAtom, nowrapAttrString, nullAtom);
    new ((void*)&objectAttr) QualifiedName(nullAtom, objectAttrString, nullAtom);
    new ((void*)&onabortAttr) QualifiedName(nullAtom, onabortAttrString, nullAtom);
    new ((void*)&onbeforecopyAttr) QualifiedName(nullAtom, onbeforecopyAttrString, nullAtom);
    new ((void*)&onbeforecutAttr) QualifiedName(nullAtom, onbeforecutAttrString, nullAtom);
    new ((void*)&onbeforepasteAttr) QualifiedName(nullAtom, onbeforepasteAttrString, nullAtom);
    new ((void*)&onbeforeunloadAttr) QualifiedName(nullAtom, onbeforeunloadAttrString, nullAtom);
    new ((void*)&onblurAttr) QualifiedName(nullAtom, onblurAttrString, nullAtom);
    new ((void*)&onchangeAttr) QualifiedName(nullAtom, onchangeAttrString, nullAtom);
    new ((void*)&onclickAttr) QualifiedName(nullAtom, onclickAttrString, nullAtom);
    new ((void*)&oncontextmenuAttr) QualifiedName(nullAtom, oncontextmenuAttrString, nullAtom);
    new ((void*)&oncopyAttr) QualifiedName(nullAtom, oncopyAttrString, nullAtom);
    new ((void*)&oncutAttr) QualifiedName(nullAtom, oncutAttrString, nullAtom);
    new ((void*)&ondblclickAttr) QualifiedName(nullAtom, ondblclickAttrString, nullAtom);
    new ((void*)&ondragAttr) QualifiedName(nullAtom, ondragAttrString, nullAtom);
    new ((void*)&ondragendAttr) QualifiedName(nullAtom, ondragendAttrString, nullAtom);
    new ((void*)&ondragenterAttr) QualifiedName(nullAtom, ondragenterAttrString, nullAtom);
    new ((void*)&ondragleaveAttr) QualifiedName(nullAtom, ondragleaveAttrString, nullAtom);
    new ((void*)&ondragoverAttr) QualifiedName(nullAtom, ondragoverAttrString, nullAtom);
    new ((void*)&ondragstartAttr) QualifiedName(nullAtom, ondragstartAttrString, nullAtom);
    new ((void*)&ondropAttr) QualifiedName(nullAtom, ondropAttrString, nullAtom);
    new ((void*)&onerrorAttr) QualifiedName(nullAtom, onerrorAttrString, nullAtom);
    new ((void*)&onfocusAttr) QualifiedName(nullAtom, onfocusAttrString, nullAtom);
    new ((void*)&oninputAttr) QualifiedName(nullAtom, oninputAttrString, nullAtom);
    new ((void*)&onkeydownAttr) QualifiedName(nullAtom, onkeydownAttrString, nullAtom);
    new ((void*)&onkeypressAttr) QualifiedName(nullAtom, onkeypressAttrString, nullAtom);
    new ((void*)&onkeyupAttr) QualifiedName(nullAtom, onkeyupAttrString, nullAtom);
    new ((void*)&onloadAttr) QualifiedName(nullAtom, onloadAttrString, nullAtom);
    new ((void*)&onmousedownAttr) QualifiedName(nullAtom, onmousedownAttrString, nullAtom);
    new ((void*)&onmousemoveAttr) QualifiedName(nullAtom, onmousemoveAttrString, nullAtom);
    new ((void*)&onmouseoutAttr) QualifiedName(nullAtom, onmouseoutAttrString, nullAtom);
    new ((void*)&onmouseoverAttr) QualifiedName(nullAtom, onmouseoverAttrString, nullAtom);
    new ((void*)&onmouseupAttr) QualifiedName(nullAtom, onmouseupAttrString, nullAtom);
    new ((void*)&onmousewheelAttr) QualifiedName(nullAtom, onmousewheelAttrString, nullAtom);
    new ((void*)&onpasteAttr) QualifiedName(nullAtom, onpasteAttrString, nullAtom);
    new ((void*)&onresetAttr) QualifiedName(nullAtom, onresetAttrString, nullAtom);
    new ((void*)&onresizeAttr) QualifiedName(nullAtom, onresizeAttrString, nullAtom);
    new ((void*)&onscrollAttr) QualifiedName(nullAtom, onscrollAttrString, nullAtom);
    new ((void*)&onsearchAttr) QualifiedName(nullAtom, onsearchAttrString, nullAtom);
    new ((void*)&onselectAttr) QualifiedName(nullAtom, onselectAttrString, nullAtom);
    new ((void*)&onselectstartAttr) QualifiedName(nullAtom, onselectstartAttrString, nullAtom);
    new ((void*)&onsubmitAttr) QualifiedName(nullAtom, onsubmitAttrString, nullAtom);
    new ((void*)&onunloadAttr) QualifiedName(nullAtom, onunloadAttrString, nullAtom);
    new ((void*)&pagexAttr) QualifiedName(nullAtom, pagexAttrString, nullAtom);
    new ((void*)&pageyAttr) QualifiedName(nullAtom, pageyAttrString, nullAtom);
    new ((void*)&placeholderAttr) QualifiedName(nullAtom, placeholderAttrString, nullAtom);
    new ((void*)&plainAttr) QualifiedName(nullAtom, plainAttrString, nullAtom);
    new ((void*)&pluginpageAttr) QualifiedName(nullAtom, pluginpageAttrString, nullAtom);
    new ((void*)&pluginspageAttr) QualifiedName(nullAtom, pluginspageAttrString, nullAtom);
    new ((void*)&pluginurlAttr) QualifiedName(nullAtom, pluginurlAttrString, nullAtom);
    new ((void*)&precisionAttr) QualifiedName(nullAtom, precisionAttrString, nullAtom);
    new ((void*)&profileAttr) QualifiedName(nullAtom, profileAttrString, nullAtom);
    new ((void*)&promptAttr) QualifiedName(nullAtom, promptAttrString, nullAtom);
    new ((void*)&readonlyAttr) QualifiedName(nullAtom, readonlyAttrString, nullAtom);
    new ((void*)&relAttr) QualifiedName(nullAtom, relAttrString, nullAtom);
    new ((void*)&resultsAttr) QualifiedName(nullAtom, resultsAttrString, nullAtom);
    new ((void*)&revAttr) QualifiedName(nullAtom, revAttrString, nullAtom);
    new ((void*)&rowsAttr) QualifiedName(nullAtom, rowsAttrString, nullAtom);
    new ((void*)&rowspanAttr) QualifiedName(nullAtom, rowspanAttrString, nullAtom);
    new ((void*)&rulesAttr) QualifiedName(nullAtom, rulesAttrString, nullAtom);
    new ((void*)&schemeAttr) QualifiedName(nullAtom, schemeAttrString, nullAtom);
    new ((void*)&scopeAttr) QualifiedName(nullAtom, scopeAttrString, nullAtom);
    new ((void*)&scrollamountAttr) QualifiedName(nullAtom, scrollamountAttrString, nullAtom);
    new ((void*)&scrolldelayAttr) QualifiedName(nullAtom, scrolldelayAttrString, nullAtom);
    new ((void*)&scrollingAttr) QualifiedName(nullAtom, scrollingAttrString, nullAtom);
    new ((void*)&selectedAttr) QualifiedName(nullAtom, selectedAttrString, nullAtom);
    new ((void*)&shapeAttr) QualifiedName(nullAtom, shapeAttrString, nullAtom);
    new ((void*)&sizeAttr) QualifiedName(nullAtom, sizeAttrString, nullAtom);
    new ((void*)&soundstartAttr) QualifiedName(nullAtom, soundstartAttrString, nullAtom);
    new ((void*)&spanAttr) QualifiedName(nullAtom, spanAttrString, nullAtom);
    new ((void*)&srcAttr) QualifiedName(nullAtom, srcAttrString, nullAtom);
    new ((void*)&standbyAttr) QualifiedName(nullAtom, standbyAttrString, nullAtom);
    new ((void*)&startAttr) QualifiedName(nullAtom, startAttrString, nullAtom);
    new ((void*)&styleAttr) QualifiedName(nullAtom, styleAttrString, nullAtom);
    new ((void*)&summaryAttr) QualifiedName(nullAtom, summaryAttrString, nullAtom);
    new ((void*)&tabindexAttr) QualifiedName(nullAtom, tabindexAttrString, nullAtom);
    new ((void*)&tableborderAttr) QualifiedName(nullAtom, tableborderAttrString, nullAtom);
    new ((void*)&targetAttr) QualifiedName(nullAtom, targetAttrString, nullAtom);
    new ((void*)&telbookAttr) QualifiedName(nullAtom, telbookAttrString, nullAtom);
    new ((void*)&textAttr) QualifiedName(nullAtom, textAttrString, nullAtom);
    new ((void*)&titleAttr) QualifiedName(nullAtom, titleAttrString, nullAtom);
    new ((void*)&topAttr) QualifiedName(nullAtom, topAttrString, nullAtom);
    new ((void*)&topmarginAttr) QualifiedName(nullAtom, topmarginAttrString, nullAtom);
    new ((void*)&truespeedAttr) QualifiedName(nullAtom, truespeedAttrString, nullAtom);
    new ((void*)&typeAttr) QualifiedName(nullAtom, typeAttrString, nullAtom);
    new ((void*)&usemapAttr) QualifiedName(nullAtom, usemapAttrString, nullAtom);
    new ((void*)&valignAttr) QualifiedName(nullAtom, valignAttrString, nullAtom);
    new ((void*)&valueAttr) QualifiedName(nullAtom, valueAttrString, nullAtom);
    new ((void*)&valuetypeAttr) QualifiedName(nullAtom, valuetypeAttrString, nullAtom);
    new ((void*)&versionAttr) QualifiedName(nullAtom, versionAttrString, nullAtom);
    new ((void*)&viewsourceAttr) QualifiedName(nullAtom, viewsourceAttrString, nullAtom);
    new ((void*)&vlinkAttr) QualifiedName(nullAtom, vlinkAttrString, nullAtom);
    new ((void*)&volumeAttr) QualifiedName(nullAtom, volumeAttrString, nullAtom);
    new ((void*)&vspaceAttr) QualifiedName(nullAtom, vspaceAttrString, nullAtom);
    new ((void*)&widthAttr) QualifiedName(nullAtom, widthAttrString, nullAtom);
    new ((void*)&wrapAttr) QualifiedName(nullAtom, wrapAttrString, nullAtom);
}
struct cleanupHtmlNames  {
    ~cleanupHtmlNames() {
    // This will destroy the AtomicString table
    // All other atomic string destruction must be done before this call

#ifndef __WINSCW__
    if( initialized ) {
        size_t num(0);
        QualifiedName** array = getHTMLTags(&num);
        for( int i=0; i<num; ++i ) {
            // Items are not void*, so we explicitly call the destructor to clean them up
            // These pointers are not deletable because they are new'ed to a fixed address
            QualifiedName* item = array[i];
            item->~QualifiedName();
        }
        array = getHTMLAttrs(&num);
        for( int i=0; i<num; ++i ) {
            // Items are not void*, so we explicitly call the destructor to clean them up
            // These pointers are not deletable because they are new'ed to a fixed address
            QualifiedName* item = array[i];
            item->~QualifiedName();
        }
    }
#endif //__WINSCW__
    
    xhtmlNSString = "";
    aTagString = "";
    abbrTagString = "";
    acronymTagString = "";
    addressTagString = "";
    appletTagString = "";
    areaTagString = "";
    bTagString = "";
    baseTagString = "";
    basefontTagString = "";
    bdoTagString = "";
    bgsoundTagString = "";
    bigTagString = "";
    blockquoteTagString = "";
    bodyTagString = "";
    brTagString = "";
    buttonTagString = "";
    canvasTagString = "";
    captionTagString = "";
    centerTagString = "";
    citeTagString = "";
    codeTagString = "";
    colTagString = "";
    colgroupTagString = "";
    ddTagString = "";
    delTagString = "";
    dfnTagString = "";
    dirTagString = "";
    divTagString = "";
    dlTagString = "";
    dtTagString = "";
    emTagString = "";
    embedTagString = "";
    fieldsetTagString = "";
    fontTagString = "";
    formTagString = "";
    frameTagString = "";
    framesetTagString = "";
    headTagString = "";
    h1TagString = "";
    h2TagString = "";
    h3TagString = "";
    h4TagString = "";
    h5TagString = "";
    h6TagString = "";
    hrTagString = "";
    htmlTagString = "";
    iTagString = "";
    iframeTagString = "";
    imageTagString = "";
    imgTagString = "";
    inputTagString = "";
    insTagString = "";
    isindexTagString = "";
    kbdTagString = "";
    keygenTagString = "";
    labelTagString = "";
    layerTagString = "";
    legendTagString = "";
    liTagString = "";
    linkTagString = "";
    listingTagString = "";
    mapTagString = "";
    marqueeTagString = "";
    menuTagString = "";
    metaTagString = "";
    nobrTagString = "";
    noembedTagString = "";
    noframesTagString = "";
    nolayerTagString = "";
    noscriptTagString = "";
    objectTagString = "";
    olTagString = "";
    optgroupTagString = "";
    optionTagString = "";
    pTagString = "";
    paramTagString = "";
    plaintextTagString = "";
    preTagString = "";
    qTagString = "";
    sTagString = "";
    sampTagString = "";
    scriptTagString = "";
    selectTagString = "";
    smallTagString = "";
    spanTagString = "";
    strikeTagString = "";
    strongTagString = "";
    styleTagString = "";
    subTagString = "";
    supTagString = "";
    tableTagString = "";
    tbodyTagString = "";
    tdTagString = "";
    textareaTagString = "";
    tfootTagString = "";
    thTagString = "";
    theadTagString = "";
    titleTagString = "";
    trTagString = "";
    ttTagString = "";
    uTagString = "";
    ulTagString = "";
    varTagString = "";
    wbrTagString = "";
    xmpTagString = "";

    abbrAttrString = "";
    accept_charsetAttrString = "";
    acceptAttrString = "";
    accesskeyAttrString = "";
    actionAttrString = "";
    alignAttrString = "";
    alinkAttrString = "";
    altAttrString = "";
    archiveAttrString = "";
    autocompleteAttrString = "";
    autosaveAttrString = "";
    axisAttrString = "";
    backgroundAttrString = "";
    behaviorAttrString = "";
    bgcolorAttrString = "";
    bgpropertiesAttrString = "";
    borderAttrString = "";
    bordercolorAttrString = "";
    cellpaddingAttrString = "";
    cellspacingAttrString = "";
    charAttrString = "";
    challengeAttrString = "";
    charoffAttrString = "";
    charsetAttrString = "";
    checkedAttrString = "";
    cellborderAttrString = "";
    citeAttrString = "";
    classAttrString = "";
    classidAttrString = "";
    clearAttrString = "";
    codeAttrString = "";
    codebaseAttrString = "";
    codetypeAttrString = "";
    colorAttrString = "";
    colsAttrString = "";
    colspanAttrString = "";
    compactAttrString = "";
    compositeAttrString = "";
    contentAttrString = "";
    contenteditableAttrString = "";
    coordsAttrString = "";
    ctiAttrString = "";
    dataAttrString = "";
    datetimeAttrString = "";
    declareAttrString = "";
    deferAttrString = "";
    dirAttrString = "";
    directionAttrString = "";
    directkeyAttrString = "";
    disabledAttrString = "";
    emailAttrString = "";
    enctypeAttrString = "";
    faceAttrString = "";
    forAttrString = "";
    frameAttrString = "";
    frameborderAttrString = "";
    headersAttrString = "";
    heightAttrString = "";
    hiddenAttrString = "";
    hrefAttrString = "";
    hreflangAttrString = "";
    hspaceAttrString = "";
    http_equivAttrString = "";
    idAttrString = "";
    incrementalAttrString = "";
    ismapAttrString = "";
    keytypeAttrString = "";
    labelAttrString = "";
    langAttrString = "";
    languageAttrString = "";
    leftAttrString = "";
    leftmarginAttrString = "";
    linkAttrString = "";
    longdescAttrString = "";
    loopAttrString = "";
    lowsrcAttrString = "";
    marginheightAttrString = "";
    marginwidthAttrString = "";
    maxAttrString = "";
    maxlengthAttrString = "";
    mayscriptAttrString = "";
    mediaAttrString = "";
    methodAttrString = "";
    minAttrString = "";
    multipleAttrString = "";
    nameAttrString = "";
    nohrefAttrString = "";
    noresizeAttrString = "";
    noshadeAttrString = "";
    nowrapAttrString = "";
    objectAttrString = "";
    onabortAttrString = "";
    onbeforecopyAttrString = "";
    onbeforecutAttrString = "";
    onbeforepasteAttrString = "";
    onbeforeunloadAttrString = "";
    onblurAttrString = "";
    onchangeAttrString = "";
    onclickAttrString = "";
    oncontextmenuAttrString = "";
    oncopyAttrString = "";
    oncutAttrString = "";
    ondblclickAttrString = "";
    ondragAttrString = "";
    ondragendAttrString = "";
    ondragenterAttrString = "";
    ondragleaveAttrString = "";
    ondragoverAttrString = "";
    ondragstartAttrString = "";
    ondropAttrString = "";
    onerrorAttrString = "";
    onfocusAttrString = "";
    oninputAttrString = "";
    onkeydownAttrString = "";
    onkeypressAttrString = "";
    onkeyupAttrString = "";
    onloadAttrString = "";
    onmousedownAttrString = "";
    onmousemoveAttrString = "";
    onmouseoutAttrString = "";
    onmouseoverAttrString = "";
    onmouseupAttrString = "";
    onmousewheelAttrString = "";
    onpasteAttrString = "";
    onresetAttrString = "";
    onresizeAttrString = "";
    onscrollAttrString = "";
    onsearchAttrString = "";
    onselectAttrString = "";
    onselectstartAttrString = "";
    onsubmitAttrString = "";
    onunloadAttrString = "";
    pagexAttrString = "";
    pageyAttrString = "";
    placeholderAttrString = "";
    plainAttrString = "";
    pluginpageAttrString = "";
    pluginspageAttrString = "";
    pluginurlAttrString = "";
    precisionAttrString = "";
    profileAttrString = "";
    promptAttrString = "";
    readonlyAttrString = "";
    relAttrString = "";
    resultsAttrString = "";
    revAttrString = "";
    rowsAttrString = "";
    rowspanAttrString = "";
    rulesAttrString = "";
    schemeAttrString = "";
    scopeAttrString = "";
    scrollamountAttrString = "";
    scrolldelayAttrString = "";
    scrollingAttrString = "";
    selectedAttrString = "";
    shapeAttrString = "";
    sizeAttrString = "";
    soundstartAttrString = "";
    spanAttrString = "";
    srcAttrString = "";
    standbyAttrString = "";
    startAttrString = "";
    styleAttrString = "";
    summaryAttrString = "";
    tabindexAttrString = "";
    tableborderAttrString = "";
    targetAttrString = "";
    telbookAttrString = "";
    textAttrString = "";
    titleAttrString = "";
    topAttrString = "";
    topmarginAttrString = "";
    truespeedAttrString = "";
    typeAttrString = "";
    usemapAttrString = "";
    valignAttrString = "";
    valueAttrString = "";
    valuetypeAttrString = "";
    versionAttrString = "";
    viewsourceAttrString = "";
    vlinkAttrString = "";
    volumeAttrString = "";
    vspaceAttrString = "";
    widthAttrString = "";
    wrapAttrString = "";

    AtomicString::remove();

    initialized = false;
    } 
};
struct cleanupHtmlNames htmlNames;

} //HTMLNames

} //WebCore
