/*
 * THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT.
 *
 *
 * Copyright (C) 2005 Apple Computer, Inc.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE COMPUTER, INC. ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL APPLE COMPUTER, INC. OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. 
 */

#include "config.h"
#ifdef AVOID_STATIC_CONSTRUCTORS
#define DOM_XMLNAMES_HIDE_GLOBALS 1
#else
#define QNAME_DEFAULT_CONSTRUCTOR 1
#endif

#include "XMLNames.h"

#include "StaticConstructors.h"
namespace WebCore { namespace XMLNames {

using namespace WebCore;

DEFINE_GLOBAL(AtomicString, xmlNamespaceURI, "http://www.w3.org/XML/1998/namespace")

// Attributes
DEFINE_GLOBAL(QualifiedName, baseAttr, nullAtom, "base", xmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, langAttr, nullAtom, "lang", xmlNamespaceURI);
DEFINE_GLOBAL(QualifiedName, spaceAttr, nullAtom, "space", xmlNamespaceURI);

static bool initialized = false;
// Attributes
static const char *xmlNSString = "http://www.w3.org/XML/1998/namespace";
static const char *baseAttrString = "base";
static const char *langAttrString = "lang";
static const char *spaceAttrString = "space";

WebCore::QualifiedName** getXMLAttrs(size_t* size)
{
    static WebCore::QualifiedName* XMLAttr[] = {
        (WebCore::QualifiedName*)&baseAttr,
        (WebCore::QualifiedName*)&langAttr,
        (WebCore::QualifiedName*)&spaceAttr,
    };
    *size = 3;
    return XMLAttr;
}

void init()
{
    if (initialized)
        return;
    initialized = true;
    
    // Use placement new to initialize the globals.
    
    AtomicString::init();
    AtomicString xmlNS(xmlNSString);

    // Namespace
    new ((void*)&xmlNamespaceURI) AtomicString(xmlNS);

    new ((void*)&baseAttr) QualifiedName(nullAtom, baseAttrString, xmlNS);
    new ((void*)&langAttr) QualifiedName(nullAtom, langAttrString, xmlNS);
    new ((void*)&spaceAttr) QualifiedName(nullAtom, spaceAttrString, xmlNS);
}
struct cleanupXmlNames  {
    ~cleanupXmlNames() {
#ifndef __WINSCW__
    if( initialized ) {
        ((AtomicString*)&xmlNamespaceURI)->~AtomicString();
        ((QualifiedName*)&baseAttr)->~QualifiedName();
        ((QualifiedName*)&langAttr)->~QualifiedName();
        ((QualifiedName*)&spaceAttr)->~QualifiedName();
    }
#endif // __WINSCW__
 
    xmlNSString = "";
    baseAttrString = "";
    langAttrString = "";
    spaceAttrString = "";
    initialized = false;
    }
};
struct cleanupXmlNames xmlNames;

} }

