//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//
//copies the config files for test case 5

PRINT Loading config UPnP_OneThread

RUN_UTILS MkDir c:\private\
RUN_UTILS MkDir c:\private\101F7988\
RUN_UTILS MkDir c:\private\101f7989\
RUN_UTILS MkDir c:\private\101f7989\ESock\


