//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

RUN_SCRIPT z:\upnp\servertests\scripts\te_upnp_test_remove_config_files.script

RUN_SCRIPT z:\upnp\servertests\scripts\te_upnp_test_copy_config_files.script
RUN_UTILS CopyFile z:\upnp\servertests\configs\esock\ip.proxy.udpserver.esk  c:\private\101f7989\ESock\ip.proxy.udpserver.esk
RUN_UTILS MakeReadWrite  c:\private\101f7989\ESock\ip.proxy.udpserver.esk

RUN_SCRIPT z:\upnp\servertests\scripts\te_upnp_udpserver.script

RUN_SCRIPT z:\upnp\servertests\scripts\te_upnp_test_remove_config_files.script
RUN_SCRIPT z:\upnp\servertests\scripts\te_upnp_test_copy_config_files.script
