# Copyright (c) 2008-2009 Nokia Corporation and/or its subsidiary(-ies).
# All rights reserved.
# This component and the accompanying materials are made available
# under the terms of "Eclipse Public License v1.0"
# which accompanies this distribution, and is available
# at the URL "http://www.eclipse.org/legal/epl-v10.html".
#
# Initial Contributors:
# Nokia Corporation - initial contribution.
#
#
# Contributors:
#
# Description:
#
upnpserviceXMLTagsstringtable UPNPSERVICEXMLTAGS
EScpd scpd
ESpecVersion specVersion
EMajorNumber major
EMinorNumber minor
EActionList actionList
EAction action
EName name
EArgumentList argumentList
EArgument argument
EArgumentDirection direction
ERelatedStateVar relatedStateVariable
ERetValue retval
EServiceStateTable serviceStateTable
EStateVariable stateVariable
EStateVariableDataType dataType
EStateVariableDefaultValue defaultValue
EAllowedValueList allowedValueList
EAllowedValue allowedValue
EAllowedValueRange allowedValueRange
EMinimumValue minimum
EMaximumValue maximum
EStepValue step
ESendEvents sendEvents
