#
# Copyright (c) 2008-2009 Nokia Corporation and/or its subsidiary(-ies).
# All rights reserved.
# This component and the accompanying materials are made available
# under the terms of "Eclipse Public License v1.0"
# which accompanies this distribution, and is available
# at the URL "http://www.eclipse.org/legal/epl-v10.html".
#
# Initial Contributors:
# Nokia Corporation - initial contribution.
#
# Contributors:
#
# Description:
#
fstringtable UPnP
#
#Standard tokens specified in UPnP Device Architecture
EInfinite infinite
ENS ns
#
#UPnP Headers
ENTS NTS
ENT NT
EUSN USN
EMX MX
EST ST
ETimeout Timeout
ESEQ SEQ
EMAN MAN
ESoapAction SoapAction
EExt Ext
ESID SID
ECallback Callback
#
#UPnP request methods
ENotify NOTIFY
EMSearch M-SEARCH
EMPost M-POST
ESubscribe SUBSCRIBE
EUnsubscribe UNSUBSCRIBE
#
#Standard constants
ETextXml text/xml
EUtf8 utf-8
EUpnpEvent upnp:event
EUpnpPropChange upnp:propchange
ESoapUrl http://schemas.xmlsoap.org/soap/envelope
ESoapHeader 01-SOAPACTION
ENsParam 01
#
#Standard response status codes
ENotFound Not Found
EBadRequest Bad request
EInternalServerError Internal Server Error
ENotImplemented Not Implemented
EPreconditionFailed Precondition Failed
EMethodNotAllowed Method Not Allowed
EOk OK
EUnsupportedMediaType Unsupported Media Type
ERequestTimeout Request Timeout
