// Copyright (c) 2008-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
// Script file for HTTP Integration Test.
// @internalAll
// 
//

PRINT UPNP_MESSAGE_TESTS

// Load the test
LOAD_SUITE upnpmessagetest


START_TESTCASE	RESPONSE_COMPOSER_TEST_1
//! @file			                            
//! @SYMTestCaseID		            UPnPMessage-POS-44
//! @SYMTestCaseDesc 	            Composer a simple response.
//! @SYMREQ						REQ10742, REQ10744
//! @SYMTestStatus 		            Implemented
//! @SYMTestPriority 		            Critical
//! @SYMTestActions 		
//!				                                •	Compose a simple response.
//!				                                •	Response has only 2 headers.
//!				                                •	Headers do not have multiple values.
//!                                                •	Headers do not have parameters.
//!                                                •	No response entity body.
//!
//! @SYMTestExpectedResults     The composer successfully composes the response using the provided data.
//!                                                The test F/W writes the composed request to epoc32/winscw/c/logs/UpnpMessageTestLogs\composedresponses.dump
//! @SYMTestType 		                UT
RUN_TEST_STEP 	100 	upnpmessagetest ResponseComposerTest z:\upnp\upnpmessagetest\ini\upnpmessagetest.ini  RESPONSE_COMPOSER_TEST_1
END_TESTCASE 	RESPONSE_COMPOSER_TEST_1



START_TESTCASE	RESPONSE_COMPOSER_TEST_2
//! @file			                            
//! @SYMTestCaseID		            UPnPMessage-POS-45
//! @SYMTestCaseDesc 	            Composer a simple response.
//! @SYMREQ						REQ10742, REQ10744
//! @SYMTestStatus 		            Implemented
//! @SYMTestPriority 		            Critical
//! @SYMTestActions 		    
//!				                                •	Compose a simple response.
//!				                                •	Response has 6 headers.
//!				                                •	Headers do not have multiple values.
//!                                                •	Headers do not have parameters.
//!                                                •	No response entity body.
//!
//! @SYMTestExpectedResults     The composer successfully composes the response using the provided data.
//!                                                The test F/W writes the composed request to epoc32/winscw/c/logs/UpnpMessageTestLogs\composedresponses.dump
//! @SYMTestType 		                UT
RUN_TEST_STEP 	100 	upnpmessagetest ResponseComposerTest z:\upnp\upnpmessagetest\ini\upnpmessagetest.ini  RESPONSE_COMPOSER_TEST_2
END_TESTCASE 	RESPONSE_COMPOSER_TEST_2



START_TESTCASE	RESPONSE_COMPOSER_TEST_3
//! @file			                            
//! @SYMTestCaseID		            UPnPMessage-POS-46
//! @SYMTestCaseDesc 	            Composer a simple response.
//! @SYMREQ						REQ10742, REQ10744
//! @SYMTestStatus 		            Implemented
//! @SYMTestPriority 		            Critical
//! @SYMTestActions 		
//!				                                •	Compose a simple response.
//!				                                •	Response has 5 headers.
//!				                                •	Headers do not have multiple values.
//!                                                •	Some have parameters.
//!                                                •	No response entity body.
//!
//! @SYMTestExpectedResults     The composer successfully composes the response using the provided data.
//!                                                The test F/W writes the composed request to epoc32/winscw/c/logs/UpnpMessageTestLogs\composedresponses.dump
//! @SYMTestType 		                UT
RUN_TEST_STEP 	100 	upnpmessagetest ResponseComposerTest z:\upnp\upnpmessagetest\ini\upnpmessagetest.ini  RESPONSE_COMPOSER_TEST_3
END_TESTCASE 	RESPONSE_COMPOSER_TEST_3



START_TESTCASE	RESPONSE_COMPOSER_TEST_4
//! @file			                            
//! @SYMTestCaseID		            UPnPMessage-POS-47
//! @SYMTestCaseDesc 	            Composer a simple response.
//! @SYMREQ						REQ10742, REQ10744
//! @SYMTestStatus 		            Implemented
//! @SYMTestPriority 		            Critical
//! @SYMTestActions 		
//!				                                •	Compose a simple response.
//!				                                •	Response has 5 headers.
//!				                                •	Headers do not have multiple values.
//!                                                •	Some have parameters.
//!                                                •	Response has a body.
//!
//! @SYMTestExpectedResults     The composer successfully composes the response using the provided data.
//!                                                The test F/W writes the composed request to epoc32/winscw/c/logs/UpnpMessageTestLogs\composedresponses.dump
//! @SYMTestType 		                UT
RUN_TEST_STEP 	100 	upnpmessagetest ResponseComposerTest z:\upnp\upnpmessagetest\ini\upnpmessagetest.ini  RESPONSE_COMPOSER_TEST_4
END_TESTCASE 	RESPONSE_COMPOSER_TEST_4
