/ UPNPMESSAGETEST_REQUEST_PARSER_TESTS_3.SCRIPT
// Copyright (c) 2008-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
// Script file for HTTP Integration Test.
// @internalAll
// 
//

PRINT UPNP_MESSAGE_TESTS

// Load the test
LOAD_SUITE upnpmessagetest


START_TESTCASE	REQUEST_PARSER_TEST_17
//! @file			                            
//! @SYMTestCaseID		            UPnPMessage-POS-39
//! @SYMTestCaseDesc 	            Parsing 2 NOTIFY request.
//! @SYMREQ						REQ10743, REQ10744
//! @SYMTestStatus 		            Implemented
//! @SYMTestPriority 		            Critical
//! @SYMTestActions 		            
//!				                                •	Parsing 2 simple NOTIFY request.
//!				                                •	2nd request appears as excess data of the 1st.
//!				                                •	Requests have no body.
//!                                                •	Request data appears in a multiple chunks.
//!
//! @SYMTestExpectedResults     The parser successfully parses the requests.
//! @SYMTestType 		                UT
RUN_TEST_STEP 	100 	upnpmessagetest RequestParserTest z:\upnp\upnpmessagetest\ini\upnpmessagetest.ini  REQUEST_PARSER_TEST_17
END_TESTCASE 	REQUEST_PARSER_TEST_17



START_TESTCASE	REQUEST_PARSER_TEST_18
//! @file			                            
//! @SYMTestCaseID		            UPnPMessage-POS-40
//! @SYMTestCaseDesc 	            Parsing a SUBSCRIBE request.
//! @SYMREQ						REQ10743, REQ10744
//! @SYMTestStatus 		            Implemented
//! @SYMTestPriority 		            Critical
//! @SYMTestActions 		
//!				                                •	Parsing a simple SUBSCRIBE request.
//!				                                •	Request has no excess data.
//!				                                •	Request has no body.
//!                                                •	Request data appears in multiple chunks.
//!
//! @SYMTestExpectedResults     The parser successfully parses the request.
//! @SYMTestType 		                UT
RUN_TEST_STEP 	100 	upnpmessagetest RequestParserTest z:\upnp\upnpmessagetest\ini\upnpmessagetest.ini  REQUEST_PARSER_TEST_18
END_TESTCASE 	REQUEST_PARSER_TEST_18



START_TESTCASE	REQUEST_PARSER_TEST_19
//! @file			                            
//! @SYMTestCaseID		            UPnPMessage-POS-41
//! @SYMTestCaseDesc 	            Parsing 2 SUBSCRIBE requests.
//! @SYMREQ						REQ10743, REQ10744
//! @SYMTestStatus 		            Implemented
//! @SYMTestPriority 		            Critical
//! @SYMTestActions 		
//!				                                •	Parsing a simple SUBSCRIBE request.
//!				                                •	2nd request appears as the excess data of the 1st.
//!				                                •	Requests have no body.
//!                                                •	Request data appears in multiple chunks.
//!
//! @SYMTestExpectedResults     The parser successfully parses the requests.
//! @SYMTestType 		                UT
RUN_TEST_STEP 	100 	upnpmessagetest RequestParserTest z:\upnp\upnpmessagetest\ini\upnpmessagetest.ini  REQUEST_PARSER_TEST_19
END_TESTCASE 	REQUEST_PARSER_TEST_19



START_TESTCASE	REQUEST_PARSER_TEST_20
//! @file			                            
//! @SYMTestCaseID		            UPnPMessage-POS-42
//! @SYMTestCaseDesc 	            Parsing a UNSUBSCRIBE request.
//! @SYMREQ						REQ10743, REQ10744
//! @SYMTestStatus 		            Implemented
//! @SYMTestPriority 		            Critical
//! @SYMTestActions 		
//!				                                •	Parsing a simple UNSUBSCRIBE request.       
//!				                                •	Request has no excess data.
//!				                                •	Request has no body.
//!                                                •	Request data appears in multiple chunks.
//!
//! @SYMTestExpectedResults     The parser successfully parses the request.
//! @SYMTestType 		                UT
RUN_TEST_STEP 	100 	upnpmessagetest RequestParserTest z:\upnp\upnpmessagetest\ini\upnpmessagetest.ini  REQUEST_PARSER_TEST_20
END_TESTCASE 	REQUEST_PARSER_TEST_20



START_TESTCASE	REQUEST_PARSER_TEST_21
//! @file			                            
//! @SYMTestCaseID		            UPnPMessage-POS-43
//! @SYMTestCaseDesc 	            Parsing 2 UNSUBSCRIBE requests.
//! @SYMREQ						REQ10743, REQ10744
//! @SYMTestStatus 		            Implemented
//! @SYMTestPriority 		            Critical
//! @SYMTestActions 		    
//!				                                •	Parsing a simple UNSUBSCRIBE request. 
//!				                                •	2nd request appears as the excess data of the 1st.
//!				                                •	Requests have no body.
//!                                                •	Request data appears in multiple chunks.
//!
//! @SYMTestExpectedResults     The parser successfully parses the requests.
//! @SYMTestType 		                UT
RUN_TEST_STEP 	100 	upnpmessagetest RequestParserTest z:\upnp\upnpmessagetest\ini\upnpmessagetest.ini  REQUEST_PARSER_TEST_21
END_TESTCASE 	REQUEST_PARSER_TEST_21
