// Copyright (c) 2008-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
// Script file for HTTP Integration Test.
// @internalAll
// 
//

PRINT UPNP_MESSAGE_TESTS

// Load the test
LOAD_SUITE upnpmessagetest


START_TESTCASE	REQUEST_PARSER_TEST_12
//! @file			                            
//! @SYMTestCaseID		            UPnPMessage-POS-34
//! @SYMTestCaseDesc 	            Parsing 2 simple M-SEARCH requests.
//! @SYMREQ						REQ10743, REQ10744
//! @SYMTestStatus 		            Implemented
//! @SYMTestPriority 		            Critical
//! @SYMTestActions 		
//!				                                •	Parsing a simple M-SEARCH request.
//!				                                •	2nd request appears as excess data of the 1st.
//!				                                •	No request entity body.
//!                                                •	Request data appears in multiple chunks.
//!
//! @SYMTestExpectedResults     The parser successfully parses the requests.
//! @SYMTestType 		                UT
RUN_TEST_STEP 	100 	upnpmessagetest RequestParserTest z:\upnp\upnpmessagetest\ini\upnpmessagetest.ini  REQUEST_PARSER_TEST_12
END_TESTCASE 	REQUEST_PARSER_TEST_12



START_TESTCASE	REQUEST_PARSER_TEST_13
//! @file			                            
//! @SYMTestCaseID		            UPnPMessage-POS-35
//! @SYMTestCaseDesc 	            Parsing a simple M-SEARCH request.
//! @SYMREQ						REQ10743, REQ10744
//! @SYMTestStatus 		            Implemented
//! @SYMTestPriority 		            Critical
//! @SYMTestActions 		
//!				                                •	Parsing a simple M-SEARCH request.
//!				                                •	Request has excess data which is not parsed.
//!				                                •	No request entity body.
//!                                                •	Request data appears in multiple chunks.
//!
//! @SYMTestExpectedResults     The parser successfully parses the request.
//! @SYMTestType 		                UT
RUN_TEST_STEP 	100 	upnpmessagetest RequestParserTest z:\upnp\upnpmessagetest\ini\upnpmessagetest.ini  REQUEST_PARSER_TEST_13
END_TESTCASE 	REQUEST_PARSER_TEST_13



START_TESTCASE	REQUEST_PARSER_TEST_14
//! @file			                            
//! @SYMTestCaseID		            UPnPMessage-NEG-36
//! @SYMTestCaseDesc 	            Parsing a M-SEARCH request that has a body
//! @SYMREQ						REQ10743, REQ10744
//! @SYMTestStatus 		            Implemented
//! @SYMTestPriority 		            Critical
//! @SYMTestActions 		
//!				                                •	Parsing a simple M-SEARCH request.
//!				                                •	Request has no excess data.
//!				                                •	Request has a body.
//!                                                 •	Request data appears in a single chunk. 
//!   
//! @SYMTestExpectedResults     Since it is invalid for M-SEARCH request to have a body, the parser returns with KErrCorrupt.
//! @SYMTestType 		                UT
RUN_TEST_STEP 	100 	upnpmessagetest RequestParserTest z:\upnp\upnpmessagetest\ini\upnpmessagetest.ini  REQUEST_PARSER_TEST_14
END_TESTCASE 	REQUEST_PARSER_TEST_14



START_TESTCASE	REQUEST_PARSER_TEST_15
//! @file			                            
//! @SYMTestCaseID		            UPnPMessage-POS-37
//! @SYMTestCaseDesc 	            Parsing a NOTIFY request.
//! @SYMREQ						REQ10743, REQ10744
//! @SYMTestStatus 		            Implemented
//! @SYMTestPriority 		            Critical
//! @SYMTestActions 		
//!				                                •	Parsing a simple NOTIFY request.
//!				                                •	Request has no excess data.
//!				                                •	Request has no body.
//!                                                •	Request data appears in a single chunk.
//!
//! @SYMTestExpectedResults     The parser successfully parses the request.
//! @SYMTestType 		                UT
RUN_TEST_STEP 	100 	upnpmessagetest RequestParserTest z:\upnp\upnpmessagetest\ini\upnpmessagetest.ini  REQUEST_PARSER_TEST_15
END_TESTCASE 	REQUEST_PARSER_TEST_15



START_TESTCASE	REQUEST_PARSER_TEST_16
//! @file			                            
//! @SYMTestCaseID		            UPnPMessage-POS-38
//! @SYMTestCaseDesc 	            Parsing a NOTIFY request.
//! @SYMREQ						REQ10743, REQ10744
//! @SYMTestStatus 		            Implemented
//! @SYMTestPriority 		            Critical
//! @SYMTestActions 		
//!				                                •	Parsing a simple NOTIFY request.
//!				                                •	Request has no excess data.
//!				                                •	Request has no body.
//!                                                •	Request data appears in a multiple chunks.
//!
//! @SYMTestExpectedResults     The parser successfully parses the request.
//! @SYMTestType 		                UT
RUN_TEST_STEP 	100 	upnpmessagetest RequestParserTest z:\upnp\upnpmessagetest\ini\upnpmessagetest.ini  REQUEST_PARSER_TEST_16
END_TESTCASE 	REQUEST_PARSER_TEST_16
