// Copyright (c) 2008-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
// Script file for HTTP Integration Test.
// @internalAll
// 
//

PRINT UPNP_MESSAGE_TESTS

// Load the test
LOAD_SUITE upnpmessagetest


START_TESTCASE	CODEC_TEST_1
//! @file			                            
//! @SYMTestCaseID		            HTTP-POS-001
//! @SYMTestCaseDesc 	            Encode the request headers.
//! @SYMREQ						REQ10744
//! @SYMTestStatus 		            Implemented
//! @SYMTestPriority 		            Critical
//! @SYMTestActions 		
//!				                                •	Test the encode functionality for the following request headers:
//!				                                    NTS, NT, USN, ST, Timeout, MX, SEQ, Callback, SoapAction, MAN
//!				                                
//! @SYMTestExpectedResults     It should be possible to set the values for these headers in the defined format.
//! @SYMTestType 		                UT
RUN_TEST_STEP 	!OOM !PanicCode=0 100 	upnpmessagetest CodecDecodeTest z:\upnp\upnpmessagetest\ini\upnpmessagetest.ini  CODEC_TEST_1
END_TESTCASE 	CODEC_TEST_1



START_TESTCASE	CODEC_TEST_2
//! @file			                            
//! @SYMTestCaseID		            HTTP-POS-002
//! @SYMTestCaseDesc 	            Encode the request headers.
//! @SYMREQ						REQ10744
//! @SYMTestStatus 		            Implemented
//! @SYMTestPriority 		            Critical
//! @SYMTestActions 		
//!				                                
//!				                                •	Test the encode functionality for the following request headers:
//!				                                    NTS, NT, USN, ST, Timeout, MX, SEQ, Callback, SoapAction
//!                                                •	Provide multiple values for the above headers.
//!
//! @SYMTestExpectedResults     It should not be possible to set multiple values for the mentioned headers.
//! @SYMTestType 		                UT
RUN_TEST_STEP 	!OOM 100 	upnpmessagetest CodecDecodeTest z:\upnp\upnpmessagetest\ini\upnpmessagetest.ini  CODEC_TEST_2
END_TESTCASE 	CODEC_TEST_2



START_TESTCASE	CODEC_TEST_3
//! @file			                            
//! @SYMTestCaseID		            HTTP-POS-003
//! @SYMTestCaseDesc 	            Decode the response headers.
//! @SYMREQ						REQ10744
//! @SYMTestStatus 		            Implemented
//! @SYMTestPriority 		            Critical
//! @SYMTestActions 		
//!				                                •	Test the decode functionality for the following response headers:
//!				                                    USN, ST, Timeout, EXT, SID
//!				                                
//! @SYMTestExpectedResults     It should be possible to get the values for these headers.
//! @SYMTestType 		                UT
RUN_TEST_STEP 	!OOM 100 	upnpmessagetest CodecDecodeTest z:\upnp\upnpmessagetest\ini\upnpmessagetest.ini  CODEC_TEST_3
END_TESTCASE 	CODEC_TEST_3



START_TESTCASE	CODEC_TEST_4
//! @file			                            
//! @SYMTestCaseID		            HTTP-POS-004
//! @SYMTestCaseDesc 	            Decode the response headers.
//! @SYMREQ						REQ10744
//! @SYMTestStatus 		            Implemented
//! @SYMTestPriority 		            Critical
//! @SYMTestActions 		
//!				                                •	Test the decode functionality for the following response headers:
//!				                                    USN, ST, Timeout, SID
//!				                                •	The above headers have multiple values.
//!    
//! @SYMTestExpectedResults     Only the first value of the each of the above headers should be retrieved.
//! @SYMTestType 		                UT
RUN_TEST_STEP 	!OOM 100 	upnpmessagetest CodecDecodeTest z:\upnp\upnpmessagetest\ini\upnpmessagetest.ini  CODEC_TEST_4
END_TESTCASE 	CODEC_TEST_4



START_TESTCASE	CODEC_TEST_5
//! @file			                            
//! @SYMTestCaseID		            HTTP-POS-007
//! @SYMTestCaseDesc 	            Decode the request headers.
//! @SYMREQ						REQ10744
//! @SYMTestStatus 		            Implemented
//! @SYMTestPriority 		            Critical
//! @SYMTestActions 		
//!				                                •	Test the decode functionality for the following request headers:
//!				                                    NTS, NT, USN, ST, Timeout, MX, SEQ, Callback, SoapAction, MAN
//!				                                
//! @SYMTestExpectedResults     It should be possible to get the values for these headers.
//! @SYMTestType 		                UT
RUN_TEST_STEP 	!OOM 100 	upnpmessagetest CodecEncodeTest z:\upnp\upnpmessagetest\ini\upnpmessagetest.ini  CODEC_TEST_5
END_TESTCASE 	CODEC_TEST_5



START_TESTCASE	CODEC_TEST_6
//! @file			                            
//! @SYMTestCaseID		            HTTP-POS-008
//! @SYMTestCaseDesc 	            Decode the request headers.
//! @SYMREQ						REQ10744
//! @SYMTestStatus 		            Implemented
//! @SYMTestPriority 		            Critical
//! @SYMTestActions 		
//!				                                •	Test the decode functionality for the following request headers:
//!				                                    NTS, NT, USN, ST, Timeout, MX, SEQ, Callback, SoapAction
//!				                                •	The above headers have multiple values.
//!
//! @SYMTestExpectedResults     Only the first value of the each of the above headers should be retrieved.
//! @SYMTestType 		                UT
RUN_TEST_STEP 	!OOM 100 	upnpmessagetest CodecEncodeTest z:\upnp\upnpmessagetest\ini\upnpmessagetest.ini  CODEC_TEST_6
END_TESTCASE 	CODEC_TEST_6



START_TESTCASE	TEST_COVERAGE
//! @file			                            
//! @SYMTestCaseID		            HTTP-POS-009
//! @SYMTestCaseDesc 	            Encode the request headers.
//! @SYMREQ						REQ10744
//! @SYMTestStatus 		            Implemented
//! @SYMTestPriority 		            Critical
//! @SYMTestActions 		
//!				                                •	Test the encode functionality for the following request headers:
//!				                                    MAN, ST, Timeout, MX, Callback, SoapAction
//!
//! @SYMTestExpectedResults     It should be possible to encode all of the above headers.
//! @SYMTestType 		                UT
RUN_TEST_STEP 	100 	upnpmessagetest CodecEncodeTest z:\upnp\upnpmessagetest\ini\upnpmessagetest.ini  TEST_COVERAGE
END_TESTCASE 	TEST_COVERAGE
