/*
* Copyright (c) 2002 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of the License "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description: 
*
*/

/*
** WARNING
**
** DO NOT EDIT - THIS CODE IS AUTOMATICALLY GENERATED
**               FROM A DATA FILE BY THE DICTIONARY CREATION PROGRAM
**
** This file generated on Wed Apr 24 14:59:12 2002
**                        (coordinated universal time)
**
** Command line: r:\Shared\shaun\dict_creator\dict_creator.exe wml_1_3.dict wml_1_3_tokendict.c wml_1_3_tokendict.h
*/
/*
** This file is generated by the dictionary creator and includes some hand-edits.
** If you need any help to edit this file please see Shaun Keller/Frank Rchichi/Ramesh Bapanapalli.
*/

/*
 * Dictionary = Wml_1_3
 * Public id = 0x0A
 * Doc Type = -//WAPFORUM//DTD WML 1.3//EN
 */
#include "nw_wml1x_wml_1_3_tokens.h"
#include "nw_wbxml_dictionary.h"


static const NW_Ucs2 NW_Wml_1_3_ElementTag_pre[] = {'p','r','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_ElementTag_a[] = {'a','\0'};
static const NW_Ucs2 NW_Wml_1_3_ElementTag_td[] = {'t','d','\0'};
static const NW_Ucs2 NW_Wml_1_3_ElementTag_tr[] = {'t','r','\0'};
static const NW_Ucs2 NW_Wml_1_3_ElementTag_table[] = {'t','a','b','l','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_ElementTag_p[] = {'p','\0'};
static const NW_Ucs2 NW_Wml_1_3_ElementTag_postfield[] = {'p','o','s','t','f','i','e','l','d','\0'};
static const NW_Ucs2 NW_Wml_1_3_ElementTag_anchor[] = {'a','n','c','h','o','r','\0'};
static const NW_Ucs2 NW_Wml_1_3_ElementTag_access[] = {'a','c','c','e','s','s','\0'};
static const NW_Ucs2 NW_Wml_1_3_ElementTag_b[] = {'b','\0'};
static const NW_Ucs2 NW_Wml_1_3_ElementTag_big[] = {'b','i','g','\0'};
static const NW_Ucs2 NW_Wml_1_3_ElementTag_br[] = {'b','r','\0'};
static const NW_Ucs2 NW_Wml_1_3_ElementTag_card[] = {'c','a','r','d','\0'};
static const NW_Ucs2 NW_Wml_1_3_ElementTag_do[] = {'d','o','\0'};
static const NW_Ucs2 NW_Wml_1_3_ElementTag_em[] = {'e','m','\0'};
static const NW_Ucs2 NW_Wml_1_3_ElementTag_fieldset[] = {'f','i','e','l','d','s','e','t','\0'};
static const NW_Ucs2 NW_Wml_1_3_ElementTag_go[] = {'g','o','\0'};
static const NW_Ucs2 NW_Wml_1_3_ElementTag_head[] = {'h','e','a','d','\0'};
static const NW_Ucs2 NW_Wml_1_3_ElementTag_i[] = {'i','\0'};
static const NW_Ucs2 NW_Wml_1_3_ElementTag_img[] = {'i','m','g','\0'};
static const NW_Ucs2 NW_Wml_1_3_ElementTag_input[] = {'i','n','p','u','t','\0'};
static const NW_Ucs2 NW_Wml_1_3_ElementTag_meta[] = {'m','e','t','a','\0'};
static const NW_Ucs2 NW_Wml_1_3_ElementTag_noop[] = {'n','o','o','p','\0'};
static const NW_Ucs2 NW_Wml_1_3_ElementTag_prev[] = {'p','r','e','v','\0'};
static const NW_Ucs2 NW_Wml_1_3_ElementTag_onevent[] = {'o','n','e','v','e','n','t','\0'};
static const NW_Ucs2 NW_Wml_1_3_ElementTag_optgroup[] = {'o','p','t','g','r','o','u','p','\0'};
static const NW_Ucs2 NW_Wml_1_3_ElementTag_option[] = {'o','p','t','i','o','n','\0'};
static const NW_Ucs2 NW_Wml_1_3_ElementTag_refresh[] = {'r','e','f','r','e','s','h','\0'};
static const NW_Ucs2 NW_Wml_1_3_ElementTag_select[] = {'s','e','l','e','c','t','\0'};
static const NW_Ucs2 NW_Wml_1_3_ElementTag_small[] = {'s','m','a','l','l','\0'};
static const NW_Ucs2 NW_Wml_1_3_ElementTag_strong[] = {'s','t','r','o','n','g','\0'};
static const NW_Ucs2 NW_Wml_1_3_ElementTag_template[] = {'t','e','m','p','l','a','t','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_ElementTag_timer[] = {'t','i','m','e','r','\0'};
static const NW_Ucs2 NW_Wml_1_3_ElementTag_u[] = {'u','\0'};
static const NW_Ucs2 NW_Wml_1_3_ElementTag_setvar[] = {'s','e','t','v','a','r','\0'};
static const NW_Ucs2 NW_Wml_1_3_ElementTag_wml[] = {'w','m','l','\0'};

/*
 * tag entries - sorted by token
 */
static const
NW_WBXML_DictEntry_t NW_Wml_1_3_tag_token_0[36] = {
	{0x1b, (NW_String_UCS2Buff_t *) NW_Wml_1_3_ElementTag_pre},
	{0x1c, (NW_String_UCS2Buff_t *) NW_Wml_1_3_ElementTag_a},
	{0x1d, (NW_String_UCS2Buff_t *) NW_Wml_1_3_ElementTag_td},
	{0x1e, (NW_String_UCS2Buff_t *) NW_Wml_1_3_ElementTag_tr},
	{0x1f, (NW_String_UCS2Buff_t *) NW_Wml_1_3_ElementTag_table},
	{0x20, (NW_String_UCS2Buff_t *) NW_Wml_1_3_ElementTag_p},
	{0x21, (NW_String_UCS2Buff_t *) NW_Wml_1_3_ElementTag_postfield},
	{0x22, (NW_String_UCS2Buff_t *) NW_Wml_1_3_ElementTag_anchor},
	{0x23, (NW_String_UCS2Buff_t *) NW_Wml_1_3_ElementTag_access},
	{0x24, (NW_String_UCS2Buff_t *) NW_Wml_1_3_ElementTag_b},
	{0x25, (NW_String_UCS2Buff_t *) NW_Wml_1_3_ElementTag_big},
	{0x26, (NW_String_UCS2Buff_t *) NW_Wml_1_3_ElementTag_br},
	{0x27, (NW_String_UCS2Buff_t *) NW_Wml_1_3_ElementTag_card},
	{0x28, (NW_String_UCS2Buff_t *) NW_Wml_1_3_ElementTag_do},
	{0x29, (NW_String_UCS2Buff_t *) NW_Wml_1_3_ElementTag_em},
	{0x2a, (NW_String_UCS2Buff_t *) NW_Wml_1_3_ElementTag_fieldset},
	{0x2b, (NW_String_UCS2Buff_t *) NW_Wml_1_3_ElementTag_go},
	{0x2c, (NW_String_UCS2Buff_t *) NW_Wml_1_3_ElementTag_head},
	{0x2d, (NW_String_UCS2Buff_t *) NW_Wml_1_3_ElementTag_i},
	{0x2e, (NW_String_UCS2Buff_t *) NW_Wml_1_3_ElementTag_img},
	{0x2f, (NW_String_UCS2Buff_t *) NW_Wml_1_3_ElementTag_input},
	{0x30, (NW_String_UCS2Buff_t *) NW_Wml_1_3_ElementTag_meta},
	{0x31, (NW_String_UCS2Buff_t *) NW_Wml_1_3_ElementTag_noop},
	{0x32, (NW_String_UCS2Buff_t *) NW_Wml_1_3_ElementTag_prev},
	{0x33, (NW_String_UCS2Buff_t *) NW_Wml_1_3_ElementTag_onevent},
	{0x34, (NW_String_UCS2Buff_t *) NW_Wml_1_3_ElementTag_optgroup},
	{0x35, (NW_String_UCS2Buff_t *) NW_Wml_1_3_ElementTag_option},
	{0x36, (NW_String_UCS2Buff_t *) NW_Wml_1_3_ElementTag_refresh},
	{0x37, (NW_String_UCS2Buff_t *) NW_Wml_1_3_ElementTag_select},
	{0x38, (NW_String_UCS2Buff_t *) NW_Wml_1_3_ElementTag_small},
	{0x39, (NW_String_UCS2Buff_t *) NW_Wml_1_3_ElementTag_strong},
	{0x3b, (NW_String_UCS2Buff_t *) NW_Wml_1_3_ElementTag_template},
	{0x3c, (NW_String_UCS2Buff_t *) NW_Wml_1_3_ElementTag_timer},
	{0x3d, (NW_String_UCS2Buff_t *) NW_Wml_1_3_ElementTag_u},
	{0x3e, (NW_String_UCS2Buff_t *) NW_Wml_1_3_ElementTag_setvar},
	{0x3f, (NW_String_UCS2Buff_t *) NW_Wml_1_3_ElementTag_wml}
};

/*
 * tag entries - sorted by name
 */
static const
NW_Uint8 NW_Wml_1_3_tag_name_0[36] = {
	1,
	8,
	7,
	9,
	10,
	11,
	12,
	13,
	14,
	15,
	16,
	17,
	18,
	19,
	20,
	21,
	22,
	24,
	25,
	26,
	5,
	6,
	0,
	23,
	27,
	28,
	34,
	29,
	30,
	4,
	2,
	31,
	32,
	3,
	33,
	35,
};

static const NW_Ucs2 NW_Wml_1_3_ElementTag_zzzunknown[] = {'z','z','z','u','n','k','n','o','w','n','\0'};

/*
 * tag entries - sorted by token
 */
static const
NW_WBXML_DictEntry_t NW_Wml_1_3_tag_token_1[1] = {
	{0x18, (NW_String_UCS2Buff_t *) NW_Wml_1_3_ElementTag_zzzunknown}
};

/*
 * tag entries - sorted by name
 */
static const
NW_Uint8 NW_Wml_1_3_tag_name_1[1] = {
	0,
};

static const NW_Ucs2 NW_Wml_1_3_AttributeTag_accept_charset[] = {'a','c','c','e','p','t','-','c','h','a','r','s','e','t','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_align_bottom[] = {'a','l','i','g','n','=','b','o','t','t','o','m','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_align_center[] = {'a','l','i','g','n','=','c','e','n','t','e','r','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_align_left[] = {'a','l','i','g','n','=','l','e','f','t','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_align_middle[] = {'a','l','i','g','n','=','m','i','d','d','l','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_align_right[] = {'a','l','i','g','n','=','r','i','g','h','t','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_align_top[] = {'a','l','i','g','n','=','t','o','p','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_alt[] = {'a','l','t','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_content[] = {'c','o','n','t','e','n','t','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_domain[] = {'d','o','m','a','i','n','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_emptyok_false[] = {'e','m','p','t','y','o','k','=','f','a','l','s','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_emptyok_true[] = {'e','m','p','t','y','o','k','=','t','r','u','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_format[] = {'f','o','r','m','a','t','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_height[] = {'h','e','i','g','h','t','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_hspace[] = {'h','s','p','a','c','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_ivalue[] = {'i','v','a','l','u','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_iname[] = {'i','n','a','m','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_label[] = {'l','a','b','e','l','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_localsrc[] = {'l','o','c','a','l','s','r','c','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_maxlength[] = {'m','a','x','l','e','n','g','t','h','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_method_get[] = {'m','e','t','h','o','d','=','g','e','t','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_method_post[] = {'m','e','t','h','o','d','=','p','o','s','t','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_mode_nowrap[] = {'m','o','d','e','=','n','o','w','r','a','p','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_mode_wrap[] = {'m','o','d','e','=','w','r','a','p','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_multiple_false[] = {'m','u','l','t','i','p','l','e','=','f','a','l','s','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_multiple_true[] = {'m','u','l','t','i','p','l','e','=','t','r','u','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_name[] = {'n','a','m','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_newcontext_false[] = {'n','e','w','c','o','n','t','e','x','t','=','f','a','l','s','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_newcontext_true[] = {'n','e','w','c','o','n','t','e','x','t','=','t','r','u','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_onpick[] = {'o','n','p','i','c','k','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_onenterbackward[] = {'o','n','e','n','t','e','r','b','a','c','k','w','a','r','d','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_onenterforward[] = {'o','n','e','n','t','e','r','f','o','r','w','a','r','d','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_ontimer[] = {'o','n','t','i','m','e','r','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_optional_false[] = {'o','p','t','i','o','n','a','l','=','f','a','l','s','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_optional_true[] = {'o','p','t','i','o','n','a','l','=','t','r','u','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_path[] = {'p','a','t','h','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_scheme[] = {'s','c','h','e','m','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_sendreferer_false[] = {'s','e','n','d','r','e','f','e','r','e','r','=','f','a','l','s','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_sendreferer_true[] = {'s','e','n','d','r','e','f','e','r','e','r','=','t','r','u','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_size[] = {'s','i','z','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_src[] = {'s','r','c','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_ordered_true[] = {'o','r','d','e','r','e','d','=','t','r','u','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_ordered_false[] = {'o','r','d','e','r','e','d','=','f','a','l','s','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_tabindex[] = {'t','a','b','i','n','d','e','x','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_title[] = {'t','i','t','l','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_type[] = {'t','y','p','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_type_accept[] = {'t','y','p','e','=','a','c','c','e','p','t','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_type_delete[] = {'t','y','p','e','=','d','e','l','e','t','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_type_help[] = {'t','y','p','e','=','h','e','l','p','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_type_password[] = {'t','y','p','e','=','p','a','s','s','w','o','r','d','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_type_onpick[] = {'t','y','p','e','=','o','n','p','i','c','k','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_type_onenterbackward[] = {'t','y','p','e','=','o','n','e','n','t','e','r','b','a','c','k','w','a','r','d','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_type_onenterforward[] = {'t','y','p','e','=','o','n','e','n','t','e','r','f','o','r','w','a','r','d','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_type_ontimer[] = {'t','y','p','e','=','o','n','t','i','m','e','r','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_zzzunknown[] = {'z','z','z','u','n','k','n','o','w','n','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_type_options[] = {'t','y','p','e','=','o','p','t','i','o','n','s','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_type_prev[] = {'t','y','p','e','=','p','r','e','v','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_type_reset[] = {'t','y','p','e','=','r','e','s','e','t','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_type_text[] = {'t','y','p','e','=','t','e','x','t','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_type_vnd_[] = {'t','y','p','e','=','v','n','d','.','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_href[] = {'h','r','e','f','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_href_http___[] = {'h','r','e','f','=','h','t','t','p',':','/','/','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_href_https___[] = {'h','r','e','f','=','h','t','t','p','s',':','/','/','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_value[] = {'v','a','l','u','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_vspace[] = {'v','s','p','a','c','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_width[] = {'w','i','d','t','h','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_xml_lang[] = {'x','m','l',':','l','a','n','g','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_align[] = {'a','l','i','g','n','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_columns[] = {'c','o','l','u','m','n','s','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_class[] = {'c','l','a','s','s','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_id[] = {'i','d','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_forua_false[] = {'f','o','r','u','a','=','f','a','l','s','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_forua_true[] = {'f','o','r','u','a','=','t','r','u','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_src_http___[] = {'s','r','c','=','h','t','t','p',':','/','/','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_src_https___[] = {'s','r','c','=','h','t','t','p','s',':','/','/','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_http_equiv[] = {'h','t','t','p','-','e','q','u','i','v','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_http_equiv_Content_Type[] = {'h','t','t','p','-','e','q','u','i','v','=','C','o','n','t','e','n','t','-','T','y','p','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_content_application_vnd_wap_wmlc_charset_[] = {'c','o','n','t','e','n','t','=','a','p','p','l','i','c','a','t','i','o','n','/','v','n','d','.','w','a','p','.','w','m','l','c',';','c','h','a','r','s','e','t','=','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_http_equiv_Expires[] = {'h','t','t','p','-','e','q','u','i','v','=','E','x','p','i','r','e','s','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_accesskey[] = {'a','c','c','e','s','s','k','e','y','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_enctype[] = {'e','n','c','t','y','p','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_enctype_application_x_www_form_urlencoded[] = {'e','n','c','t','y','p','e','=','a','p','p','l','i','c','a','t','i','o','n','/','x','-','w','w','w','-','f','o','r','m','-','u','r','l','e','n','c','o','d','e','d','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_enctype_multipart_form_data[] = {'e','n','c','t','y','p','e','=','m','u','l','t','i','p','a','r','t','/','f','o','r','m','-','d','a','t','a','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_xml_space_preserve[] = {'x','m','l',':','s','p','a','c','e','=','p','r','e','s','e','r','v','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_xml_space_default[] = {'x','m','l',':','s','p','a','c','e','=','d','e','f','a','u','l','t','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_cache_control_no_cache[] = {'c','a','c','h','e','-','c','o','n','t','r','o','l','=','n','o','-','c','a','c','h','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_cache_control[] = {'c','a','c','h','e','-','c','o','n','t','r','o','l','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_emptyok[] = {'e','m','p','t','y','o','k','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_forua[] = {'f','o','r','u','a','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_method[] = {'m','e','t','h','o','d','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_mode[] = {'m','o','d','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_multiple[] = {'m','u','l','t','i','p','l','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_optional[] = {'o','p','t','i','o','n','a','l','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_newcontext[] = {'n','e','w','c','o','n','t','e','x','t','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_ordered[] = {'o','r','d','e','r','e','d','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_sendreferer[] = {'s','e','n','d','r','e','f','e','r','e','r','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_xml_space[] = {'x','m','l',':','s','p','a','c','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag__com_[] = {'.','c','o','m','/','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag__edu_[] = {'.','e','d','u','/','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag__net_[] = {'.','n','e','t','/','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag__org_[] = {'.','o','r','g','/','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_accept[] = {'a','c','c','e','p','t','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_bottom[] = {'b','o','t','t','o','m','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_clear[] = {'c','l','e','a','r','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_delete[] = {'d','e','l','e','t','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_help[] = {'h','e','l','p','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_http___[] = {'h','t','t','p',':','/','/','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_http___www_[] = {'h','t','t','p',':','/','/','w','w','w','.','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_https___[] = {'h','t','t','p','s',':','/','/','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_https___www_[] = {'h','t','t','p','s',':','/','/','w','w','w','.','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_middle[] = {'m','i','d','d','l','e','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_nowrap[] = {'n','o','w','r','a','p','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_options[] = {'o','p','t','i','o','n','s','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_password[] = {'p','a','s','s','w','o','r','d','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_reset[] = {'r','e','s','e','t','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_text[] = {'t','e','x','t','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_top[] = {'t','o','p','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_unknown[] = {'u','n','k','n','o','w','n','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_wrap[] = {'w','r','a','p','\0'};
static const NW_Ucs2 NW_Wml_1_3_AttributeTag_www_[] = {'w','w','w','.','\0'};
/*
** The following 4 definisions are to handle duplicated tag names.
** This duplication is due to having the same "tag name" for attribute name and value.
*/

#define  NW_Wml_1_3_AttributeValueTag_onpick NW_Wml_1_3_AttributeTag_onpick
#define  NW_Wml_1_3_AttributeValueTag_onenterbackward NW_Wml_1_3_AttributeTag_onenterbackward
#define  NW_Wml_1_3_AttributeValueTag_onenterforward NW_Wml_1_3_AttributeTag_onenterforward
#define  NW_Wml_1_3_AttributeValueTag_ontimer NW_Wml_1_3_AttributeTag_ontimer

/*
 * attribute entries - sorted by token
 */
static const
NW_WBXML_DictEntry_t NW_Wml_1_3_attribute_token_0[124] = {
	{0x05, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_accept_charset},
	{0x06, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_align_bottom},
	{0x07, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_align_center},
	{0x08, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_align_left},
	{0x09, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_align_middle},
	{0x0a, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_align_right},
	{0x0b, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_align_top},
	{0x0c, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_alt},
	{0x0d, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_content},
	{0x0f, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_domain},
	{0x10, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_emptyok_false},
	{0x11, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_emptyok_true},
	{0x12, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_format},
	{0x13, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_height},
	{0x14, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_hspace},
	{0x15, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_ivalue},
	{0x16, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_iname},
	{0x18, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_label},
	{0x19, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_localsrc},
	{0x1a, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_maxlength},
	{0x1b, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_method_get},
	{0x1c, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_method_post},
	{0x1d, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_mode_nowrap},
	{0x1e, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_mode_wrap},
	{0x1f, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_multiple_false},
	{0x20, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_multiple_true},
	{0x21, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_name},
	{0x22, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_newcontext_false},
	{0x23, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_newcontext_true},
	{0x24, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_onpick},
	{0x25, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_onenterbackward},
	{0x26, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_onenterforward},
	{0x27, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_ontimer},
	{0x28, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_optional_false},
	{0x29, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_optional_true},
	{0x2a, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_path},
	{0x2e, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_scheme},
	{0x2f, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_sendreferer_false},
	{0x30, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_sendreferer_true},
	{0x31, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_size},
	{0x32, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_src},
	{0x33, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_ordered_true},
	{0x34, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_ordered_false},
	{0x35, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_tabindex},
	{0x36, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_title},
	{0x37, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_type},
	{0x38, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_type_accept},
	{0x39, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_type_delete},
	{0x3a, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_type_help},
	{0x3b, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_type_password},
	{0x3c, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_type_onpick},
	{0x3d, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_type_onenterbackward},
	{0x3e, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_type_onenterforward},
	{0x3f, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_type_ontimer},
	{0x40, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_zzzunknown},
	{0x45, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_type_options},
	{0x46, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_type_prev},
	{0x47, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_type_reset},
	{0x48, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_type_text},
	{0x49, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_type_vnd_},
	{0x4a, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_href},
	{0x4b, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_href_http___},
	{0x4c, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_href_https___},
	{0x4d, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_value},
	{0x4e, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_vspace},
	{0x4f, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_width},
	{0x50, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_xml_lang},
	{0x52, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_align},
	{0x53, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_columns},
	{0x54, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_class},
	{0x55, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_id},
	{0x56, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_forua_false},
	{0x57, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_forua_true},
	{0x58, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_src_http___},
	{0x59, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_src_https___},
	{0x5a, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_http_equiv},
	{0x5b, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_http_equiv_Content_Type},
	{0x5c, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_content_application_vnd_wap_wmlc_charset_},
	{0x5d, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_http_equiv_Expires},
	{0x5e, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_accesskey},
	{0x5f, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_enctype},
	{0x60, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_enctype_application_x_www_form_urlencoded},
	{0x61, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_enctype_multipart_form_data},
	{0x62, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_xml_space_preserve},
	{0x63, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_xml_space_default},
	{0x64, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_cache_control_no_cache},
	{0x65, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_cache_control},
	{0x66, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_emptyok},
	{0x67, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_forua},
	{0x68, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_method},
	{0x69, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_mode},
	{0x6a, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_multiple},
	{0x6b, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_optional},
	{0x6c, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_newcontext},
	{0x6d, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_ordered},
	{0x6e, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_sendreferer},
	{0x6f, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_xml_space},
	{0x85, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag__com_},
	{0x86, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag__edu_},
	{0x87, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag__net_},
	{0x88, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag__org_},
	{0x89, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_accept},
	{0x8a, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_bottom},
	{0x8b, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_clear},
	{0x8c, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_delete},
	{0x8d, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_help},
	{0x8e, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_http___},
	{0x8f, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_http___www_},
	{0x90, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_https___},
	{0x91, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_https___www_},
	{0x93, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_middle},
	{0x94, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_nowrap},
	{0x95, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeValueTag_onpick},
	{0x96, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeValueTag_onenterbackward},
	{0x97, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeValueTag_onenterforward},
	{0x98, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeValueTag_ontimer},
	{0x99, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_options},
	{0x9a, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_password},
	{0x9b, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_reset},
	{0x9d, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_text},
	{0x9e, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_top},
	{0x9f, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_unknown},
	{0xa0, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_wrap},
	{0xa1, (NW_String_UCS2Buff_t *) NW_Wml_1_3_AttributeTag_www_}
};

/*
 * attribute entries - sorted by name
 */
static const
NW_Uint8 NW_Wml_1_3_attribute_name_0[124] = {
	97,
	98,
	99,
	100,
	101,
	0,
	79,
	67,
	1,
	2,
	3,
	4,
	5,
	6,
	7,
	102,
	86,
	85,
	69,
	103,
	68,
	8,
	77,
	104,
	9,
	87,
	10,
	11,
	80,
	81,
	82,
	12,
	88,
	71,
	72,
	13,
	105,
	60,
	61,
	62,
	14,
	75,
	76,
	78,
	106,
	107,
	108,
	109,
	70,
	16,
	15,
	17,
	18,
	19,
	89,
	20,
	21,
	110,
	90,
	22,
	23,
	91,
	24,
	25,
	26,
	93,
	27,
	28,
	111,
	30,
	113,
	31,
	114,
	29,
	112,
	32,
	115,
	92,
	33,
	34,
	116,
	94,
	42,
	41,
	117,
	35,
	118,
	36,
	95,
	37,
	38,
	39,
	40,
	73,
	74,
	43,
	119,
	44,
	120,
	45,
	46,
	47,
	48,
	51,
	52,
	50,
	53,
	55,
	49,
	56,
	57,
	58,
	59,
	121,
	63,
	64,
	65,
	122,
	123,
	66,
	96,
	84,
	83,
	54,
};
/*
 * Tag codepage table
 */
static const
NW_WBXML_Codepage_t NW_Wml_1_3_tag_codepages[2] = {
	{36, (NW_WBXML_DictEntry_t*)&NW_Wml_1_3_tag_token_0[0], (NW_Byte *)&NW_Wml_1_3_tag_name_0[0]},
	{1, (NW_WBXML_DictEntry_t*)&NW_Wml_1_3_tag_token_1[0], (NW_Byte *)&NW_Wml_1_3_tag_name_1[0]},
};

/*
 * Attribute codepage table
 */
static const
NW_WBXML_Codepage_t NW_Wml_1_3_attribute_codepages[1] = {
	{124, (NW_WBXML_DictEntry_t*)&NW_Wml_1_3_attribute_token_0[0], (NW_Byte *)&NW_Wml_1_3_attribute_name_0[0]},
};

static const NW_Ucs2 NW_Wml_1_0_docType[] = {'-','/','/','W','A','P','F','O','R','U','M','/','/','D','T','D',' ','W','M','L',' ','1','.','0','/','/','E','N','\0'};
static const NW_Ucs2 NW_Wml_1_1_docType[] = {'-','/','/','W','A','P','F','O','R','U','M','/','/','D','T','D',' ','W','M','L',' ','1','.','1','/','/','E','N','\0'};
static const NW_Ucs2 NW_Wml_1_2_docType[] = {'-','/','/','W','A','P','F','O','R','U','M','/','/','D','T','D',' ','W','M','L',' ','1','.','2','/','/','E','N','\0'};
static const NW_Ucs2 NW_Wml_1_3_docType[] = {'-','/','/','W','A','P','F','O','R','U','M','/','/','D','T','D',' ','W','M','L',' ','1','.','3','/','/','E','N','\0'};

/*
 * Dictionaries
 */
const NW_WBXML_Dictionary_t NW_Wml_1_0_WBXMLDictionary = {
	NW_Wml_1_0_PublicId,
	(NW_Ucs2 *)NW_Wml_1_0_docType,
	2, (NW_WBXML_Codepage_t*)&NW_Wml_1_3_tag_codepages[0],
	1, (NW_WBXML_Codepage_t*)&NW_Wml_1_3_attribute_codepages[0],
};

const NW_WBXML_Dictionary_t NW_Wml_1_1_WBXMLDictionary = {
	NW_Wml_1_1_PublicId,
	(NW_Ucs2 *)NW_Wml_1_1_docType,
	2, (NW_WBXML_Codepage_t*)&NW_Wml_1_3_tag_codepages[0],
	1, (NW_WBXML_Codepage_t*)&NW_Wml_1_3_attribute_codepages[0],
};

const NW_WBXML_Dictionary_t NW_Wml_1_2_WBXMLDictionary = {
	NW_Wml_1_2_PublicId,
	(NW_Ucs2 *)NW_Wml_1_2_docType,
	2, (NW_WBXML_Codepage_t*)&NW_Wml_1_3_tag_codepages[0],
	1, (NW_WBXML_Codepage_t*)&NW_Wml_1_3_attribute_codepages[0],
};

const NW_WBXML_Dictionary_t NW_Wml_1_3_WBXMLDictionary = {
	NW_Wml_1_3_PublicId,
	(NW_Ucs2 *)NW_Wml_1_3_docType,
	2, (NW_WBXML_Codepage_t*)&NW_Wml_1_3_tag_codepages[0],
	1, (NW_WBXML_Codepage_t*)&NW_Wml_1_3_attribute_codepages[0],
};

/*
** WARNING
**
** DO NOT EDIT - THIS CODE IS AUTOMATICALLY GENERATED
**               FROM A DATA FILE BY THE DICTIONARY CREATION PROGRAM
**
** This file generated on Wed Apr 24 14:59:12 2002
**                        (coordinated universal time)
**
** Command line: r:\Shared\shaun\dict_creator\dict_creator.exe wml_1_3.dict wml_1_3_tokendict.c wml_1_3_tokendict.h
*/

